source/clear-containers/architecture-overview.rst
The page was using bad ReST reference stricture producing broken links.
This commit uses ReST cross reference by labels.
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>
=> fix bad link on cc-architecture-overview

source/clear-linux/network/network-bonding.rst, source/clear-linux/network/network.rst
Add a guide for network bonding, including systemd network
configuration.
Signed-off-by: Brett T. Warden <brett.t.warden@intel.com>
=> network: Add guide for network bonding

source/clear-linux/network/network-bonding.rst
Adjusted guide to use numbered process steps, removed invalid :caption:
parameter on code-block sections, plus some clarification edits and
80-character line length formatting
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>
=> network: techwriter pass on network bonding guide

source/clear-linux/getting-started/bootable-usb.rst
Do not use -v with xzcat based on experience with it causing issues
since the verbose output sometimes gets piped to the dd command.
=> clear-linux: Update bootable-usb xzcat command option

source/clear-linux/tutorials/bare-metal-install/bare-metal-install.rst
Removing the '-v' option from the xzcat command line due
to verbose output getting piped into the dd command causing
corruption on image creation.
Based on previous PR[1].
[1]-https://github.com/01org/clear-linux-documentation/pull/6
=> clear-linux: update bare-metal-install xzcat command option

source/clear-linux/how-to/swupd/run.rst
Documentation recommends the user to access swupd the man page for
further details, however user may not have /usr/bin/man command
installed, so document that he/she needs to install 'sysadmin-basic'
bundle prior to actually accessing the man-page.
=> clear-linux: ensure user have 'man' command prior running man swupd.

source/clear-linux/how-to/validate-signatures.rst
To verify the Manifest.MoM, the signature of the Manifest.MoM should be compared with the Swupd certificate, not the Clear Linux certificate.  Also, adding a section for manually validating the Swupd certificate so that it matches the section for manually validating the Clear Linux certificate.  Making the distinction between the Clear Linux certificate and the Swupd certificate more clear.
=> Correct update content validation commands

source/clear-linux/tutorials/wordpress.rst
The website does not support important notices, therfore the notice had to
change to a note.
=> Change notice from important to note on the Wordpress tutorial.

.gitignore
Fix the build directory path in the gitignore file.
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>
=> gitignore: fix build directory

source/clear-linux/how-to/mixer.rst
Moved from clearlinux/ister to bryteise/ister (at least for now).
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>
=> Fix ister link

source/clear-linux/bundles/openssh-server.rst
Use "mkdir -p" to avoid failure when some part in the middle of the
path doesn't exist (this is currently the case with a freshly
installed Clear 16820).
Add instruction to reload the systemd configuration, otherwise the
OPTIONS line won't be used and the subsystem won't work.
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>
=> Fix instructions for openssh-server bundle doc

source/clear-linux/tutorials/web-server-install/web-server-install.rst, source/clear-linux/tutorials/wp-install/wp-install.rst
Update the LAMP tutorial to add additional steps to customize the Apache configuration and locate the DocumentRoot in the /var/www/html directory to satisfy stateless requirements and changed all references from the /usr/share/httpd/htdocs directory to /var/www/html in both the LAMP server tutorial as well as the WordPress tutorial
=> Clear lamp server mods

source/clear-linux/bundles/kvm-host.rst
This commit adds general information about the kvm-host
bundle content and how to enable/start some services
that may be required when this bundle is installed.
=> clear-linux: Add information about kvm-host bundle.

source/clear-containers/architecture-overview.rst, source/clear-containers/getting-started.rst
Updates the content to link to the information in the Intel Clear Containers GitHub.
=> Update Clear Containers docs to release 3.0

source/clear-linux/get-started/compatibility-check.rst, source/clear-linux/reference/system-requirements.rst
Set requirements to reflect those instructions that gcc will use when
building for the westmere target architecture as that is how Clear
Linux is currently being built.
=> Update cpu instruction set requirements

source/clear-linux/tutorials/multi-boot/multi-boot.rst
This document added screenshots without using the figure directive.
Thus, the captions did not have the correct CSS class.
I applied the figure directive and removed the substitutions.
The captions now have the appropriate CSS class in HTML.
=> Fix figures on Multi-boot tutorial.

source/clear-linux/get-started/virtual-machine-install/kvm.rst
On 2017-Dec-15:
---------------
Fixed a couple of a apt-get commands that were missing the "install" option.
=> Fix 2 apt-get commands missing "install" option.  

source/clear-linux/get-started/virtual-machine-install/kvm.rst
Update bundle to "desktop-apps-extras" instead of "desktop-apps" to install VNC viewer on Clear Linux environment.
=> update bundle name to add VNC viewer

source/clear-linux/tutorials/aws-web/aws-web.rst
Using `root@` and then `-l clear` is ambiguous.
=> Fix ssh username passing comment.

source/clear-linux/tutorials/aws-web/aws-web.rst
Changing explanatory text to match the given example command, as corrected in #90.
=> aws-web: remove mention of -l parameter from text

source/clear-linux/tutorials/spark.rst, source/clear-linux/tutorials/tutorials.rst
This tutorial walks the user through the process of installing, configuring, and running Apache* Spark on Clear Linux OS for Intel(r) Architecture.
Signed-off-by: Jose Lamego <jose.a.lamego@intel.com>
=> spark.rst: Add standalone-Spark use case tutorial

source/clear-linux/guides/maintenance/enable-user-space.rst
I added a note that might confuse new users when following the getting started sequence download, import vmware VM->enable user space. The linux error will not indicate that the hard drive isn't big enough. The link did not render in the preview for some reason so edit it to conform with your relative links convention and build before pulling.
=> Added note to increase size of VM partition

source/clear-linux/tutorials/telemetry-backend/telemetry-backend.rst
Updated the link for intel's privacy policy to https://www.intel.com/content/www/us/en/privacy/intel-privacy-notice.html
=> Fixed link in telemetry tutorial

source/clear-linux/tutorials/telemetry-backend/telemetry-backend.rst
The intel privacy link was still not rendering correctly since the label had a "'s" in it.  I renamed it to "Intel privacy policies"
=> update privacy policy reference link

source/clear-linux/guides/maintenance/enable-user-space.rst
- Changes all input commands to use 'bash'
- Simplifies verbiage on swupd bundle-add os-clr-on-clr
- Corrects word-wrap to 78
- Corrects formatting on Note, lines 91-96
- Omits unused URI, as result of PR 124
=> Revises commands, corrects formatting, and simplifies.

source/clear-linux/reference/bundles/bundles.html
- http://kojiclear.jf.intel.com/cgit/projects/bundle-tools¸ ./gendocs.sh
- script provided by matthew johnson, https://github.com/clearlinux/clear-linux-documentation/issues/126
=> Rebuilds bundle.html manually combining two scripts:

source/clear-linux/get-started/virtual-machine-install/virtualbox.rst
Updating virtual box installation document to reflect latest LTS
kernel version (4.14) released on Nov 2017.
=> Change the lts version of kernel for virtual box

source/clear-linux/guides/maintenance/maintenance.rst, source/clear-linux/guides/maintenance/mixin.rst
Reword and rewrite the swupdaddpkg.rst documentation for the new mixin
tool and outline new features. The mixin tool is meant to replace
swupd-add-pkg and provide a new capability of adding remote RPM
repositories to the local mix.
=> Deprecate swupd-add-pkg for mixin

source/clear-linux/get-started/bootable-usb/bootable-usb-mac.rst
- Revises include statement to exclude table
- Removes unused 'releases' link
=> Revises to specify image file types used for bootable usb drive on Mac.

source/clear-linux/guides/maintenance/mixin.rst
The /usr/share/mix/rpms directory is no longer used by mixer/mixin.
Instead use the appropriate default /usr/share/mix/local-rpms directory
because this is where mixer looks for local RPMs when initializing the
local repository.
This fixes a **bug** in the documentation.
=> mixin: fix local-rpm documentation

source/clear-linux/guides/maintenance/mixin.rst
Add information for latest functionality of the mixin package
subcommand. The --bundle flag allows users to specify the name of the
bundle they add their package to.
=> mixin: add --bundle flag information

source/clear-linux/concepts/swupd-about.rst
The autoupdate subcommand has been around for a very long time now and
should be used instead of the systemctl masking commands.
=> swupd: fix autoupdate documentation

source/clear-linux/concepts/mixer-about.rst
Fixed some typos and removed trailing carriage returns. After a local build links are fixed in both concepts.rst and mixer-about.rst.
=> Concepts syntax

source/clear-linux/reference/bundle-commands.rst
- Add command to search for bundles and reference to online bundle-list
- Add swupd help as additional information
- Reformat commands with switches but no parameters as commands instead of code-blocks
=> Add swupd search and help to bundle commands reference

source/clear-linux/tutorials/docker/docker.rst
No space after period was causing |CL| substitution not to expand
=> Fix minor syntax error blocking substitution

source/clear-linux/guides/maintenance/download-verify-uncompress-linux.rst, source/clear-linux/guides/maintenance/validate-signatures.rst
Most users will not need to check the certificate, but it is worth having a link to the certificate and the method for checking it should the user wish to do so. 
Details: Added a reference to validate-signatures.rst to download-verify-uncompress-linux.rst for uniformity (issue 163). Made a couple wording changes to validate-signatures.rst and added a label to help with navigation.
=> Fix for issue #163 - lack of uniformity for validating image integrity

source/clear-linux/tutorials/kata.rst, source/clear-linux/tutorials/tutorials.rst
This tutorial describes how to install, configure and run Kata Containers on
Clear Linux.
Signed-off-by: Jose Lamego <jose.a.lamego@intel.com>
=> kata-containers: add tutorial

source/clear-linux/concepts/swupd-about.rst
This was a "not a sentence error" as the document label was awkward to use in a sentence.
=> fixed issue 162

source/clear-linux/tutorials/kata.rst
=> Removes instances of s/cc-runtime for kata per @devimc

source/clear-linux/guides/maintenance/mixer.rst
- Simplifies and combines two mix workflows at start
- Fixes Sphinx syntax
- Replaces incorrect link to web server in section CONTENTURL, VERSIONURL
=> Adds nginx web-server to show how to host mixer updates.

source/clear-linux/concepts/autospec-about.rst, source/clear-linux/guides/maintenance/autospec.rst
- where it appears in autospec-about
- where it is used in the "include"
=> Appends ':' to the end of the target-label

source/clear-linux/concepts/restart.rst, source/clear-linux/concepts/swupd-about.rst, source/clear-linux/guides/maintenance/bulk-provision.rst, source/clear-linux/guides/maintenance/mixer.rst, source/clear-linux/guides/maintenance/swupd-guide.rst, source/clear-linux/reference/collaboration/documentation/documentation.rst, source/clear-linux/reference/collaboration/documentation/inline.rst, source/clear-linux/reference/reference.rst, source/clear-linux/tutorials/azure.rst, source/clear-linux/tutorials/docker/docker.rst, source/clear-linux/tutorials/fmv.rst, source/clear-linux/tutorials/multi-boot/multi-boot.rst, source/clear-linux/tutorials/telemetry-backend/telemetry-backend.rst, source/conf.py
Fixes include the following:
1. Fixed :option: usage in concepts/restart.rst
1. Fixed broken link in /concepts/swupd-about.rst
1. Fixed mis-labaled code-blocks in maintenance/bulk-provision.rst
1. Fixed :option: usage in guides/maintenance/mixer.rst
1. Fixed broken link in guides/maintenance/swupd-guide.rst
1. Fixed broken links in reference/collaboration/documentation/documentation.rst
1. Updated :option: usage guidelines in reference/collaboration/documentation/inline.rst
1. Added page that was not included in TOC in reference/reference.rst
1. Fixed :option: usage in tutorials/azure.rst
1. Fixed :option: usage in tutorials/docker/docker.rst
1. Fixed mis-labeled code-blocks in tutorials/fmv.rst and replaced hard coded line numbers with auto generated
1. Fixed footnotes in …
=> Fixed last of the warnings in the Sphinx Build

source/clear-linux/reference/compatible-hardware.rst
As discussed removed extra processor mentions and shifted other TM * to better match standard usage
=> Fixed TM and brand references

source/clear-linux/tutorials/fmv.rst
Assembly blocks aren't recognized by lexer, so I changed it to "::"
=> asm code-block is not recognized by sphinx 1.2.2

source/clear-linux/concepts/swupd-about.rst
- Updated intro, emphasis on introducing CL update compared to traditional update
- Removed the (repeated) definition of the traditional way, already used elsewhere
- Removed intro paragraph heading to be more consistent with layout of other concept pages
- Added link to bundles page from bundles section
- Moved 'using swupd' link to Updating section (from bottom of page where it came after mixer discussion)
=> Revised intro on Software update concepts page

source/clear-linux/guides/maintenance/swupd-search.rst
=> Omit internal doc TOC; only two subheads, unnecessary.

source/clear-linux/get-started/virtual-machine-install/virtualbox.rst
- Replace "Install VirtualBox" with Prerequisites
- Add new hyperlink to troubleshoot enabling VT on IA (previous link unhelpful)
- Replace section  "Linux Guest Additions" with note on LTS integration.
=> Update VirtualBox get-started to reflect changes to CL kernel LTS 4.14:

source/clear-linux/guides/maintenance/mixer.rst
* Changed directory name for mixer workspace where the workspace is given
a path and further in the document the workspace path different, this
leads to an error when using correct procedure specified in document.
This change uses the same directory path.
* Fix for a typo where the correct default value for a configuration
file name is incorrect and when copying value from document will lead to
errors when following proper procedure specified in document.
Signed-off-by: Alex Jaramillo <alex.v.jaramillo@intel.com>
=> Fix for document inconsistencies

source/index.rst
=> Omits toctree ref to clear-containers; resets maxdepth to 1.

source/clear-linux/tutorials/machine-learning/machine-learning.rst
- Update tutorial title to indicate what it will teach
- Simplify introduction
- Update CL name substitutions
- Update section title "Additional resources" to use standard "Related topics"
- Replace "Install and configure Clear Linux Host.." title with "Prerequisites". Update section to be more consistent with other prereq sections e.g. tutorial assumption and instruction to update CL.
- Correct section title delineation with correct depth
=> Update machine learning tutorial title and content clean up

source/clear-linux/reference/bundles/openssh-server.rst
This commit documents how to change the OpenSSH port on Clear Linux*.
Clear Linux* enables an `sshd.socket` systemd unit, which listens in
port 22 by default.
This commit fixes #261
=> Document how to change OpenSSH default port.

source/clear-linux/tutorials/kubernetes.rst, source/clear-linux/tutorials/tutorials.rst
This tutorial describes how to install, configure, and run the Kubernetes
system on Cler Linux OS using either the Kubernetes runtime interface
CRI-O and kata-runtime or Docker* and runc.
This PR supersedes both #245 and #248 
Signed-off-by: Jose Lamego <jose.a.lamego@intel.com>
=> kubernetes: Add tutorial

source/clear-linux/guides/maintenance/bulk-provision.rst
bulk-provision.rst contains example URLs that were not meant to be links. Used `` to render them as inline code. Also made a small wording change to add clarity.
=> fixed example URLs that were not supposed to be hyperlinks

source/clear-linux/guides/maintenance/enable-user-space.rst
No need to install os-clr-on-clr bundle when all we need is sudo, the sysadmin-basic bundle seemed much more appropriate hear.
Signed-off-by: odwdinc <anthony.pray@gmail.com>
=> removed depends on os-clr-on-clr

source/clear-linux/reference/collaboration/documentation/rest.rst
@mvincerx since you’re the last person to work on this, I figured I’d run it by you.
There is one broken link that impacts two files: rest.rst and cross.rst (since it includes content from rest.rst)
The link that’s broken is this one: http://www.sphinx-doc.org/en/stable/markup/index.html
I’d like to replace it with: http://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html
=> fixed link to sphinx-doc.org

source/clear-linux/guides/maintenance/autospec.rst
- Remove custom mix prereq
- Remove note re install, in favor of more standard prepreq text
- Remove whitespace
- Add related topics
- Add summary end sentence directing user to next possible steps
- Remove include of overview of autospec concept. Move 'for detailed explanation...' to intro (this includes link to concept).
- Remove mixer section and skip to links to mixer section.
- Add Option 1, 2, 3 to the 3 options to build RPMs (to clarify where option starts/ends)
- Replace 'run this' and 'install this' with specifics in tooling instructions
- Minor edits to intro for each build option
=> Update Autospec guide for clarity

source/clear-linux/concepts/autospec-about.rst
- Get rid of whitespace
- Simplify intro (use training as ref)
- Remove overview heading to be consistent with other pages
- Remove list of control files in preference of existing table of common control files and ref to complete list in readme
- Add Related topics at end of article
- Remove unused overview section incl markers (no references after update to autospec guide)
- Table of example control files updated to show only files to control dependencies (a logical group of control files, rather than a mix)
- Move control files into its own section at end
- Update section How autospec works to include Note bullets in the steps to give picture of complete workflow
=> Autospec concept updates

source/clear-linux/tutorials/tutorials.rst
Remove hidden from toctree. Update maxdepth to 1.
=> Re-enable show toctree for tutorials landing page.

source/clear-linux/tutorials/greengrass.rst
- Removes metadata from embedded tags
- Changes from `<item>` to ``<item>`` where previous syntax failures occurred.
=> Greengrass tutorial: Resolves syntax errors, which cause build errors.

source/clear-linux/reference/bundles/bundles.html
- Root cause unknown; likely PHP- or Drupal-related changes made
- Inline styles are overwritten by higher-level css
- Previous PR 277 did NOT include any edits to bundle.html
=> bundles.html: removes inline styles to address error:

source/clear-linux/reference/bundle-commands.rst, source/clear-linux/reference/bundles/bundles.rst, source/clear-linux/reference/collaboration/collaboration.rst, source/clear-linux/reference/collaboration/documentation/code.rst, source/clear-linux/reference/collaboration/documentation/contents.rst, source/clear-linux/reference/collaboration/documentation/cross.rst, source/clear-linux/reference/collaboration/documentation/documentation.rst, source/clear-linux/reference/collaboration/documentation/grammar.rst, source/clear-linux/reference/collaboration/documentation/headings.rst, source/clear-linux/reference/collaboration/documentation/images.rst, source/clear-linux/reference/collaboration/documentation/inline.rst, source/clear-linux/reference/collaboration/documentation/language.rst, source/clear-linux/reference/collaboration/documentation/punctuation.rst, source/clear-linux/reference/collaboration/documentation/rest.rst, source/clear-linux/reference/collaboration/documentation/simple.rst, source/clear-linux/reference/collaboration/documentation/structures.rst, source/clear-linux/reference/collaboration/documentation/tables.rst, source/clear-linux/reference/compatible-hardware.rst, source/clear-linux/reference/compatible-kernels.rst, source/clear-linux/reference/how-to-clear-overview.rst, source/clear-linux/reference/image-types.rst, source/clear-linux/reference/reference.rst, source/clear-linux/reference/system-requirements.rst
-Replace instances of CLOSIA substitution with CL-ATTR.
-Replace in-line use of Clear Linux with CL.
-Clean up white space.
-Limited clean up in collab section, in pref of future rework
-Set landing page toctree to use maxdepth 1
=> Update product name substitution in reference section

source/clear-linux/tutorials/greengrass.rst
- Reordered Converting Deep Learning Models section to occur after CL install
- Removed instruction to add ggc_user and ggc_group as they are already present in CL
- Added links for Alexnet model and xml file
- Specified which configuration AWS Greengrass core software should be downloaded
- Fixed model directory path in model optimizer example for object detection
- Various other phrasing changes
Signed-off-by: Patrick Foley <patrick.foley@intel.com>
=> Greengrass tutorial: Tutorial structure change, link updates, phrasing changes for clarity

source/substitutions.txt
A previous PR removed the last use of the CLOSIA substitution. This PR removes the definition of the substitution entirely.
=> Remove unused CLOSIA substitution definition

source/clear-linux/get-started/bare-metal-install-beta/bare-metal-install-beta.rst
=> Escapes http://address:port in bare-metal-install-beta; example, not link

source/clear-linux/guides/maintenance/validate-signatures.rst
Clear Linux ships OpenSSL 1.1.  As a part of this transition from
OpenSSL 1.0, a new option needs passed to the command used to validate
the chain of trust.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Add OpenSSL 1.1 support for image validation

source/clear-linux/guides/network/ipxe-install.rst
Fixes a `#` which must have gotten replaced with `sudo`
=> ipxe-install: Fix ipxe_boot_script.ipxe

source/clear-linux/get-started/get-started.rst
Right now the sitenav shows nothing beneath the pre-install and everything else appears below install. The sitenav needs toctrees to accurately represent the structure. This change will make sure the appearance of the get-started page matches the structure seen on the page with the exception of system requirements, which is a ref.
=> change to getstarted to improve compatibility with sitenav

source/clear-linux/tutorials/dlrs.rst
The Kubeflow and DLRS projects made upstream changes that should be
reflected in the documentation.
This commit introduces the following changes:
* Kubeflow version 0.3.2 -> 0.4.1
* 'ks generate' now uses the --image flag so DLRS prototypes receive
image names as parameters
* Replacing ” with "
* Installing the kubeflow/tf-training registry as it's required for
deploying TFJobs
* Replacing kubeflow/core with kubeflow/common
Signed-off-by: Daniela Plascencia <daniela.plascencia@linux.intel.com>
=> dlrs.rst: Updates DLRS tutorial

source/scripts/_python/linkcheck/parse-link-check.py
This fixes a failure to convert int to string for output when an unexpected bad link is detected.
=> fixed minor bug in parse-link-check.py

source/clear-linux/reference/bundles/openssh-server.rst, source/clear-linux/reference/openssh-server.rst, source/clear-linux/reference/reference.rst
Back by popular demand....
This continues @puneetse's and @odwdinc 's work from Oct. 2018.  
I validated content; added Prereq section; added `sudo` where needed for consistency. Please validate.
=> openssh-server: Brings back doc for sftp and X11 forwarding

source/clear-linux/get-started/bare-metal-install-beta/bare-metal-install-beta.rst
- Omit requirement to login as root to set password from admin
- Per release of https://github.com/clearlinux/clr-installer/pull/213
=> Align with Engineering to lock root if sudo/admin enabled

source/clear-linux/get-started/virtual-machine-install/kvm.rst
Step 1 actually is a configuration step, it does not enable SSH. Besides that, the server has to be started.
=> kvm: Configure and start SSH server

source/clear-linux/get-started/virtual-machine-install/kvm.rst
swupd bundle-add tigervnc is enough to install a vncviewer (5MB vs 125 MB of desktop-apps-extras)
=> kvm: Simplify step to install vncviewer

source/clear-linux/guides/maintenance/architect-lifecycle.rst
Rushing this PR out. FYI only. 1 char fix. 
=> Adds missing `_` leading space before file name; root cause image failure

source/clear-linux/reference/reference.rst
=> Remove older unused openssh-server ref from toctree.

source/_themes/clearlinux/header.html, source/clear-linux/get-started/bare-metal-install-beta/bare-metal-install-beta.rst, source/clear-linux/get-started/bare-metal-install/bare-metal-install.rst, source/clear-linux/get-started/compatibility-check.rst, source/clear-linux/get-started/live-image.rst, source/clear-linux/get-started/virtual-machine-install/hyper-v.rst, source/clear-linux/get-started/virtual-machine-install/kvm.rst, source/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer.rst, source/clear-linux/get-started/virtual-machine-install/virtualbox.rst, source/clear-linux/get-started/virtual-machine-install/vmw-player-preconf.rst, source/clear-linux/get-started/virtual-machine-install/vmw-player.rst, source/clear-linux/get-started/virtual-machine-install/vmware-esxi-install-cl.rst, source/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst, source/clear-linux/guides/deploy-at-scale.rst, source/clear-linux/guides/maintenance/increase-virtual-disk-size.rst, source/clear-linux/guides/maintenance/kernel-development.rst, source/clear-linux/guides/maintenance/swupd-guide.rst, source/clear-linux/guides/maintenance/validate-signatures.rst, source/clear-linux/guides/network/dpdk.rst, source/clear-linux/guides/network/ipxe-install.rst, source/clear-linux/reference/image-types.rst, source/clear-linux/tutorials/multi-boot/multi-boot.rst
Update all links pointing at https://download.clearlinux.org to use
the CDN, i.e. https://cdn.download.clearlinux.org
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
=> Update all links to the download website to use the CDN

source/clear-linux/get-started/bootable-usb/bootable-usb.rst, source/substitutions.txt
Update the 'Create a bootable USB drive' manual with an additional caution to prevent users from errors that may occur when the USB drive partitions are not properly unmounted before burning an image, and allow them to correct the issues if they occur.
Also, update the example burning command to improve its performance and progress output.
=> Bootable USB

source/clear-linux/tutorials/azure.rst
removed '$' from bash sections to enable the copy/paste to work without edit.
=> cleaning up bash commands to make copy/paste cleaner

source/clear-linux/guides/maintenance/mixer.rst
There are 3 instances of http://localhost in the updated mixer.rst document, which were being interpreted as links by Sphinx. They are now escaped.
=> Fixes broken links found in weekly linkcheck

source/scripts/_python/requirements.txt
- Address CVE: https://nvd.nist.gov/vuln/detail/CVE-2019-8341
=> CVE patch. Update requirements.txt to Jinja2-2.11.dev0.

source/clear-linux/tutorials/docker/docker.rst, source/clear-linux/tutorials/kata.rst
- 50-runtime.conf file automatically created on CL builds > 27000
- Adds Troubleshooting, and adds prev manual conf option
- Closes #453
=> kata: removes configuration step /etc/systemd/system/docker.service.d/50-runtime .conf

source/clear-linux/guides/maintenance/fix-broken-install.rst
This PR:
- Fixes the command in fix-broken-install.rst to verify the mounted root partition is a Clear Linux partition. The current command is incorrect because it checks a file from the temporarily booted live OS, not the mounted partition to repair. 
- Minor elaboration on mounting step for clarity.
=> Update command to verify CL root partition in fix-broken-install.rst 

source/clear-linux/tutorials/nvidia.rst
Found it during link checking. The link is formatted as a URL reference but needed to use :ref: for internal link.
=> Fixed incorrectly formed link that was resulting in 404

source/clear-linux/guides/deploy-at-scale.rst, source/clear-linux/guides/tooling/swupd-guide.rst
Fixed broken links to now non-existant page: https://clearlinux.org/containers
=> Repairs links broken be removing https://clearlinux.org/containers

source/scripts/_python/linkcheck/link-whitelist.txt, source/scripts/_python/linkcheck/parse-link-check.py
Updated parse-link-check.py script to ignore anchors. 
Motivation:
1. Anchors in .rst files in GitHub are considered broken by the tester though they resolve correctly when manually clicking through on the browser.
2. Broken anchors should not block the site from being built.
3. There are now 3 categories in broken_links.html
1. unmatched broken links
2. broken links on the white list
3. broken anchors
=> Update to parse-link-check.py

source/clear-linux/guides/tooling/autospec.rst
The correct identifier for the Intel Open Source license is just "Intel" not "Intel Corporation"
=> Fix license in autospec example.

source/clear-linux/concepts/swupd-about.rst, source/clear-linux/guides/maintenance/fix-broken-install.rst, source/clear-linux/guides/network/custom-clear-container.rst, source/clear-linux/guides/tooling/autospec.rst, source/clear-linux/guides/tooling/swupd-guide.rst, source/clear-linux/tutorials/kata.rst, source/clear-linux/tutorials/nvidia.rst
- Closes #522
- Deprecates use of:
`swupd verify`
`swupd verify --fix`
`swupd verify --install`
`-m / --manifest`
=> Replaces `swupd verify` and related flag commands per #522.

source/clear-linux/concepts/telemetry-about.rst, source/clear-linux/guides/telemetrics/telem-guide.rst
Responding to comment in forums -- this will clarify that the telemetry client is disabled until the user chooses to enable it, whether at install or later.
=> Add statement to clarify enable/disable default status of client

source/clear-linux/reference/image-types.rst
container-host-kvm.img is considered developmental and should not be
shown in documentation.  Want to keep list of image types in
documentation oriented toward production.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Remove non-production image types

source/clear-linux/tutorials/nvidia.rst
One character change (.) that was missed causing the numbered list not to render.
=> Fix minor syntax on nvidia.rst

source/clear-linux/guides/tooling/autospec.rst, source/clear-linux/guides/tooling/debug.rst, source/clear-linux/guides/tooling/ister.rst, source/clear-linux/guides/tooling/mixer.rst, source/clear-linux/guides/tooling/swupd-guide.rst
Basic link clean up in advance of translation of content.
- Removed unused links
- Updated links defined as named refs to use simple text e.g. name of linked content
instead of narrative text.
- Minor text edits to accomodate minor changes to name ref links.
=> Tooling link clean up

source/clear-linux/guides/maintenance/architect-lifecycle.rst, source/clear-linux/guides/maintenance/bulk-provision.rst, source/clear-linux/guides/maintenance/cpu-performance.rst, source/clear-linux/guides/maintenance/developer-workstation.rst, source/clear-linux/guides/maintenance/enable-user-space.rst, source/clear-linux/guides/maintenance/kernel-development.rst, source/clear-linux/guides/maintenance/kernel-modules-dkms.rst, source/clear-linux/guides/maintenance/kernel-modules.rst
- Remove unused links
- Updated links  defined as named refs to use simple text e.g. name of linked content
instead of narrative text
- Minor edits to accomodate minor changes to name of ref links
=> Maintenance Guides: Basic link clean up in advance of translation of content

source/clear-linux/get-started/virtual-machine-install/gce.rst, source/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer.rst
- Items clearly referring to an element in a GUI (e.g. buttons, menus,
areas in GUI/screen) updated to use :guilabel: or :menuselection: as
apprpriate.
=> Clean up of syntax around gui elements in preparation for translation.

source/clear-linux/get-started/virtual-machine-install/vmw-player-preconf.rst, source/clear-linux/guides/maintenance/kernel-development.rst, source/clear-linux/guides/tooling/stateless.rst
A `grep '\.[A-Z]'` showed up a few places where there was a space
missing after a full stop.
Initiall spotted reading the 'stateless' guide.
A similar grep for missing spaces after commas turned up nothing.
Signed-off-by: Graham Whaley <graham.whaley@intel.com>
=> docs: Missing spaces after '.'s

source/index.rst
=> Update "Use Cases" to be "Use case tutorials"

.travis.yml, source/_scripts/_python/linkcheck/parse-link-check.py
linkcheck will automatically check for broken links. It will not error, however, as we do not want broken links to block deployment as external links can be down for a variety of reasons.
=> Turned on linkcheck in Travis.

source/guides/clear/swupd.rst
- Removes `bundle-add`
- Removes [-b] flag; deprecated
=> Corrects swupd search command; cleanup for migration

source/guides/kernel/kernel-development.rst
This PR:
- Changes the RPM spec file codeblocks to use the spec pygments formatting, add line numbers, and emphasize important lines.
- Cleans up miscellaneous RST line length warnings along the way
=> Update kernel-development codeblocks

.travis.yml
Linkcheck takes a while and only needs to happen on deployment, so added to before_deploy.
=> Linkcheck will now only happen on deployment.

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Fixed CSS problem where a bullet list inside of an admonition was being overlapped by the admonition text. Thanks @krisdale 
see: https://docs.01.org/clearlinux/latest/guides/maintenance/assign-static-ip.html
=> Fixes rendering of bullet lists in an admonition (Note).

source/_themes/otc_tcs_sphinx_theme/layout.html, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css, source/substitutions.txt
* Changed Clear Linux Project to all uppercase in substitutions.txt
* Removed link at left of header that went to clearlinux.org
* Added "home" button on right side of header that goes to clearlinux.org
=> Updates to documentation header.

checkwork.sh
=> Adds a convenience script for building and reviewing the docs locally.

.travis.yml
Part of staged move to making language content static between tagged language releases.
* creates a release consisting of a zipped archive of the html for Chinese language
Stage 2 will build language content but only deploy from the zipped archive.
=>  Stage 1 of back end support for keeping Chinese language content static in rolling release

.travis.yml, source/Makefile
* Master is now deploying only the latest tagged release of simplified Chinese into /source/_build/html/zh_CN.
* Both Chinese and English are built for error checking purposes only (parallel dirs /source/_build/html and /source/_build/zh_CN).
* Next stage will be to move building of simplified Chinese to https://github.com/clearlinux/clear-linux-documentation-zh-CN only and use latest release from that repo.
=> Deploy simplified Chinese from tagged release only

source/guides/maintenance/custom-clear-container.rst, source/guides/network/assign-static-ip.rst, source/guides/network/time.rst
This PR revises a few documents in/out of the networking guides section. It:
- Moves the static-ip document inside the network section (previously under maintenance) 
- Moves the NTP/time document inside the network section (previously under maintenance) 
- Moves the how to create CL-based docker image outside the networking section (to maintenance)
- Fix miscellaneous RST warnings
=> Move guides inside networking section

source/guides/kernel/kernel-development.rst
This PR updates the clr-boot-manager commands to call update before setting kernel to flush and pending changes to disk and optionally recommends increasing the bootlader timeout for convenience.
Closes https://github.com/clearlinux/clear-linux-documentation/issues/728
=> Update kernel development document clr-boot-manager commands

source/_themes/otc_tcs_sphinx_theme/layout.html, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
* Changed underline of search box to white from black.
* Added white border to differentiate clearlinux.org nav elements from docs. Limitations:
* Current solution fails to work 100% in responsive mode.
* Degradation is graceful.
* Better fix requires deeper change to the theme.
* Pending update pulling RTD theme into the project will allow this.
Changes to be committed:
modified:   source/_themes/otc_tcs_sphinx_theme/layout.html
modified:   source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
=> UI improvements:

source/tutorials/apache-spark.rst
- modified standardized introduction paragraph and description
- simplified prerequisites section
=> apache-spark.rst: Editorial and organizational changes

source/tutorials/redis.rst
- added standardized introduction paragraph and description
- reworded some awkward phrases
- standardized spelling of Redis and Redis-server
- disclaimed third-party trademarks/brands
=> redis.rst: Editorial changes

source/guides/stacks/dlrs.rst
* Removes "Kubeflow multi-node benchmarks" section as the steps there
reference deprecated methods/code
* Updates TF Benchmarks branch 1.12 --> 1.13 on "TensorFlow single and
multi-node benchmarks" section
Signed-off-by: Daniela Plascencia <daniela.plascencia@linux.intel.com>
=> guides/dlrs.rst: updates Kubeflow sections on DLRS guide

source/guides/stacks/dars.rst
Adds PySpark examples and points reader to the stacks/usecases repository for walkthrough with Scala. Also cleans up & reorders use/build Docker image section.   Closes #793
=> Add useage examples to DARS guide

source/get-started/bootable-usb.rst
- Present tense
- Added step to close Rufus
- Clarified final step to eject the drive name
=> bootable-usb.rst: editorial changes

source/guides/clear/stateless.rst, source/guides/kernel/firmware.rst
Adds a new document on firmware laoding and a reference to it from the stateless document.
Similar documentation for comparison:
- https://wiki.ubuntu.com/Kernel/Firmware
- https://wiki.gentoo.org/wiki/Linux_firmware
- https://wiki.archlinux.org/index.php/Microcode
Closes https://github.com/clearlinux/clear-linux-documentation/issues/800
=> Add document on firmware

source/guides/maintenance/container-image-modify.rst, source/guides/maintenance/container-image-new.rst, source/tutorials/docker.rst
=> New doc: create custom application container image

source/guides/network/firewall.rst
This PR adds a document describing firewall options in CL.
Closes https://github.com/clearlinux/clear-linux-documentation/issues/541
=> Add a document describing firewall options

source/reference/collaboration/collaboration.rst
=> Fixes broken link to clearlinux dev mailing list.

source/guides/clear/autoproxy.rst
- Fix example commands that were split into two snippets (should be one)
- Spelling corrections and minor edits for readability
Fixes #795
=> Correct example commands in autoproxy guide

source/tutorials/multi-boot/dual-boot-win.rst
Removed the space between the :command: and the text
=> typo fix for :command: directive

source/guides/maintenance/container-image-new.rst
The --version flag points to an old version of Clear Linux, and is not necessary.
=> Remove -version flag from os-install command

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Code blocks that do not have labels remain the same as before. Currently the  "none" code block is the only type in the docs that does not have a handler. 
Known issues:
1. Code blocks that do not have a label and have line numbers turned on will be mis-aligned. Currently no instances of this.
2. When line numbers are turned on the code block label appears to the right of the line numbers:
Current list of code blocks with labels:
* yaml
* bash
* console
* reStructuredText
* Python
* PowerShell
* Diff
* C
* json
* spec
* Perl
* PHP
* xml
=> Adds labels for code blocks used in Clear Linux docs

source/guides/maintenance/container-image-modify.rst
This PR consolidate and update examples and cleans up RST syntax warnings along the way.
Previously 2 multi-stage build examples exists: redis (2 layers) and cgit (3 layers). This was confusing because the cgit example was unrelated to the redis example, but used steps done in it to complete successfully. The redis example has been removed in favor of one reference example.
=> Update modify container images document

source/reference/system-requirements.rst
Remove AES requirement from the recommended minimum system requirements.
AES has been removed as a hard requirement for installation.
Closes #840
=> Remove AES requirement from Sys Req doc

source/guides/stacks/dlrs.rst
This adds a separate section for using kubectl back into the document to support CSP use cases where kubectl is all that is needed.  The section is pulled from a previous release of this doc.
=> Add kubectl section for basic use case verification

source/guides/network/dpdk.rst
- Replace network-basic-dev w/ dpdk, devepkg-dpdk
- Revise instances of linuxapp to linux and other commands
- Align with https://github.com/clearlinux/distribution/issues/1266
- Closes GH-822
=> Update compatible version to CL-31130; replace bundles to install in dpdk

source/tutorials/php.rst, source/tutorials/wordpress/web-server-install.rst
@puneetse please take a look, does this need more info on php-fpm? Do I need to add anything for people who have |CL| older than 31020 for forcing PHP to read /etc/php.d paths? 
@MCamp859 does it read ok?  It feels choppy to me, I'd be happy for any suggestions.
=> Add tutorial for PHP install & config

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Fixes a problem caused by there being two ways of indicating reStructuredText code blocks:
* rst
* rest
Now both are handled gracefully.
=> Fix in tcs_theme.css for rest code blocks.

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.js
Discovered this in another project. Verified that this solution works to three deep collapsible sections.
Documents impacted:
* Mixer (5 sections in reference section):  https://docs.01.org/clearlinux/latest/guides/clear/mixer.html#references
Changes:
* tcs_theme.css
* removed transition from CSS as this was blocking the fix from working properly. Removing it also
has no perceivable impact to the expanding and contracting of sections.
* tcs_theme.js (see note below explaining why the whole doc appears to have changed)
* added function that refreshes the `max-height` attribute of all the collapsible sections from the bottom to the top of the doc (lines 16-27). 
* added call of function in the button listener that fires when sections are expanded (line 68).
Note: Somehow Windows line …
=> Fixes a problem where nested collapsible sections do not expand correctly.

source/guides/clear/stateless.rst
besides `/var`, `/etc` and `/home`, users are allowed to make
local installations in `/usr/local` without getting swupd
operations to remove such content.
be excplicit about `/usr/local` in the stateless guide.
Relates to https://github.com/clearlinux/distribution/issues/1475
=> guides/clear/stateless: specify /usr/local as user owned

source/_scripts/_python/linkcheck/link-whitelist.txt
The following links consistently report as failing but manual checks show them working:
* https://www.intel.com/content/www/us/en/architecture-and-technology/optane-technology/optane-for-data-centers.html
* https://downloadcenter.intel.com/download/28695/Intel-Server-Board-S2600WF-Family-BIOS-and-Firmware-Update-Package-for-UEFI
* https://software.intel.com/en-us/articles/quick-start-guide-configure-intel-optane-dc-persistent-memory-on-linux
* https://software.intel.com/en-us/articles/configure-manage-and-profile-intel-optane-dc-persistent-memory-modules
=> Added 4 links to linkcheck whitelist

source/guides/stacks/mers.rst
=> Correct ext. GitHub link; correct syntax of int. link to building custom Docker image in mers

source/get-started/ipxe-install.rst
Fixes reference URLS that were being automatically turned into active links that don't go anywhere.
Simple fix - escape the URL by adding "\".
=> Fixes links that appear to be broken.

source/guides/stacks/dlrs.rst
-This pr doesn't close pr 896 because multiple files need to be edited. Last PR will close pr 896.
=> dlrs.rst: Fixes Figure caption indent (see pr 896)

source/guides/network/dpdk.rst
- This PR doesn't close pr 896 because there are multiple files to be fixed. Last PR will close pr 896.
=> dpdk.rst: Fixes Figure caption indent (see pr 896)

source/guides/maintenance/download-verify-decompress.rst
The command fails (on my computer) unless the hash algorithm is passed as uppercase.
As per https://answers.microsoft.com/en-us/windows/forum/all/certutil-hashfile-sha1-failed/1a9f31fa-bdf5-4c63-8e72-91608606ba14
Also, I didn't try to modify line 176 and I don't think I did, but for some reason, it shows up on the diff.
=> Windows command sha512 -> SHA512

source/guides/network/vnc.rst
Starting with Figure 5 (was Figure 6) through to Figure 9 (was Figure 10)
=> vnc.rst: corrected figure numbering to be sequential

source/tutorials/multi-boot/dual-boot-linux.rst, source/tutorials/multi-boot/multi-boot.rst
Add dual-boot-linux link to the multi-boot doc.
=> Add how to boot Clear via GRUB.

source/get-started/bare-metal-install-server.rst, source/guides/network/wifi.rst
This PR updates the note about wireless connections in the live-server getting started guide. Particularly, it adds an achor reference to the recently published configure wifi guide and moves the note to a logical place for the needed order of operations.
=> Update note on wireless in live-server getting started

source/_themes/otc_tcs_sphinx_theme/layout.html, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css, source/conf.py, source/index.rst
1. Updated landing page to emulate look and feel of docs page on clearlinux.org
2. Added Trademarks, Cookies, and Privacy Terms links to footer with some css formatting
3. Added some CSS to pre-emptively remove added formatting to definition list entries in sphinx/rtd theme in version 2 and above
=> Update landing page

source/guides/kernel/firmware.rst, source/tutorials/broadcom.rst
This PR adds a document about Broadcom drivers on Clear Linux. It also adds an anchor and small update to the firmware document.
closes https://github.com/clearlinux/clear-linux-documentation/issues/684
=> Add document for Broadcom drivers

source/get-started/bootable-usb.rst
=> Revise `dd` command to clarify and avoid misinterpretation in bootable-usb.

source/guides/kernel/kernel-modules-dkms.rst
Correct capitalization of DKMS to make standard with rest of doc.
Remove extra use of :abbr: (per contribe guide).
=> Fix minor text/formatting errors in DKMS kernel module guide.

source/guides/clear/mixer.rst
In Example 7:
- Remove 'tutorial' subsection as it was not clear that it was an example of the
advanced example of manual format bump.
- Roll existing tutorial content under 'advanced' as it is the advanced example.
- Result is a basic and advance example for Example 7: execute format bump
=> Minor edit to mixer guide for clarity

source/get-started/virtual-machine-install/vmw-player.rst
=> Fix missing backslashes for Windows path in vmw-player

source/guides/clear/swupd.rst
On my computer, `swupd search <term>` is the command which worked.
=> Fix typo: s/bundle <search term>/search <term>/

source/tutorials/nvidia-cuda.rst
The current CUDA Toolkit is v10.2 and now supports gcc8. I was able to install it only when the --samples option was removed. This is advice from https://community.clearlinux.org/t/cuda-toolkit-installation-error/1699
=> update to current settings

source/get-started/bare-metal-install-desktop.rst, source/get-started/bare-metal-install-server.rst
Support for f2fs file system type was enabled in the clr-installer release 2.4.1.
https://github.com/clearlinux/clr-installer/pull/654
=> Note support for f2fs for clr-installer

source/get-started/bare-metal-install-desktop.rst
- TCS follow-on to GH-1056
- Match exatcly syntax in bare-metal-install-desktop
- Improve UI legibility in HTML
=> Adds ticks, File System descriptors, Default part schema, bare-metal-install-desktop

source/tutorials/nvidia-cuda.rst
its the small things that matter, 2 missing hyphens; fixing them turned my symlinks from red to green.  I only hope these are the correct names!
=> Correct filenames

source/get-started/containers/container-images.rst, source/get-started/index.rst
This PR adds a page under get-started section for Clear Linux OS container images.
=> Add container images to  get-started page

source/tutorials/nvidia.rst
During installation, `ld.so.conf` was modified to include `/etc/ld.so.conf.d`, under which
a file `nvidia.conf` was created so that `ld` looks for shared library installed by NVIDIA driver.
This commit adds information on removing `nvidia.conf` file.
Users could optionally remove the line `include /etc/ld.so.conf.d/*.conf` that we added to
`/etc/ld.so.conf`.
=> nvidia.rst: Add a section to restore ld.so.conf

source/tutorials/nvidia.rst
Desktop files should be created under `$HOME/.local/share/applications` instead of `$HOME/.local/share`,
at least on my system only the former one works.
This commit fixed the path for both installation and uninstallation.
=> nvidia.rst: Correct the path for desktop files

source/tutorials/nvidia.rst
With `sudo sh NVIDIA-Linux-x86_64-<VERSION>.run`, we don't need to change its permission.
This commit makes it a bit more convenient for users.
=> nvidia.rst: Remove `chmod +x` on installer

source/guides/stacks/dlrs.rst
Signed-off-by: Anthony Pray anthony.s.pray@intel.com
When using the docker image you may see error
"Failed to install x of x"
ruining  "swupd clean" will fix the problems.
=> Added fix for swupd bundle-add Error

source/guides/clear/mixer.rst, source/guides/maintenance/developer-workstation.rst
Added escape character so they aren't turned into links:
guides/clear/mixer.rst:1127:
[broken] http:/
guides/clear/swupd-3rd-party.rst:61:
[broken] http:/
Pointed to containers and bundles that still exist:
guides/maintenance/developer-workstation.rst:58:
[broken] https://clearlinux.org/software/docker/machine-learning/
guides/maintenance/developer-workstation.rst:187:
[broken] https://clearlinux.org/software/bundle/web-server-basic
guides/maintenance/developer-workstation.rst:193:
[broken] https://clearlinux.org/software/bundle/database-basic
Unable to fix - this document doesn't appear to exist. Recommend removing reference.
guides/stacks/dbrs.rst:41:
[broken] https://clearlinux.org/news-blogs/database-reference-stack-dbrs-v2-now-available
Signed-off-by: Kevin Putnam …
=> Fixed broken links

source/guides/kernel/kernel-modules-dkms.rst, source/guides/kernel/kernel-modules.rst
Add the path to kernel source headers in kernel module documentation for reference.
Closes https://github.com/clearlinux/clear-linux-documentation/issues/1058
=> Add path to kernel source headers

source/guides/stacks/mers.rst
MeRS uses the open source OpenVINO not the Intel® Distribution of OpenVINO™ toolkit
=> Fix version of OpenVINO and branding on Media Reference Stack

source/reference/system-requirements.rst
- Aligns minimum system requirements with:
- https://github.com/clearlinux/clr-installer/releases/tag/2.4.3
- Closes #1103.
=> Add caution admonition to introduce option to skip-validation-size in sys-reqs.

source/guides/stacks/dlrs.rst
Adding distilbert example, and the user does not need to install tensorflow or pytorch, but upgrade transformers library.
=> update transformers section

source/guides/stacks/hpcrs.rst
Closes #1119 
Adds HPCRS guide for multi-node benchmark and converting DLRS docker container to Singularity.
=> Add HPCRS guide to Stacks guides.

source/tutorials/kubernetes.rst
This PR is a major update and revision to the order of concepts and consolidating commands to make the document more readable. There are still known complexities and issues with the process over all. This PR is not meant to address all issues or be the final set of instructions. It is meant to take a step in the direction we want to go.
Most notably it:
- Presents Kubernetes concepts in order of understanding with reference material pulled out and away from the main tutorial. 
- Adds the cloud-native-setup scripts as the first option since they have been bundled in Clear Linux.
- Adds docker and containerd options for container runtimes
Related to: https://github.com/clearlinux/clear-linux-documentation/issues/894
Related to: https://github.com/clearlinux/clear-linux-documentation/issues/1 …
=> Revise kubernetes documentation

source/about.rst
This PR updates the list of display managers available in the about page to align with the announced refocusing. 
Closes https://github.com/clearlinux/clear-linux-documentation/issues/1158
=> Update list of display managers on about page

source/guides/stacks/dlrs.rst
=> Escapes local host link, so it isn't turned into active link.

source/guides/stacks/mers.rst
The PR updates the MeRS page with information about the V2 release, examples, information on adding AOM support, and updates to new Intel Stacks locations.
Closes #1159
Closes #1142
Closes #1098
=> Update MeRS page for V2 release

source/guides/kernel/kernel-modules-dkms.rst, source/tutorials/zfs.rst
- Closes #1192 
- Docs should follow DRY and be modular. Use include directive where possible and feasible
=> Add include in ZFS tutorial to reference kernel-module-dkms

source/reference/system-requirements.rst
- https://github.com/clearlinux/clr-installer/pull/666
- Closes #1207
Signed-off-by: michael vincerra <michael.vincerra@intel.com>
=> Remove UEFI requirement per clr-installer release.

source/tutorials/kubernetes.rst
The create_stack.sh script requires git to complete fully. Perhaps this should be added to the setup_system.sh script, but until it does, this change allows the steps to complete without error.
=> add dep for create_stack.sh kubernetes script

source/conf.py, source/guides/clear/k8-migration.rst, source/guides/clear/k8s-migration.rst
This guide provides direction in upgrade Kubernetes from 1.17.x release up to 1.19.x release due to Clear missing the 1.18.x release.
=> guides: Add new Kubernetes migration guide

source/tutorials/kubernetes.rst
You can see it currently goes to `https://docs.01.org/clearlinux/latest/tutorials/Useyourcluster`. It needs `<#use-your-cluster>` for the link to generate correctly.
=> Fix #use-your-cluster link on kubernetes docs

source/tutorials/lamp-server.rst
database-basic is no longer used, there is a mariadb package now.
Closes #1226
=> Fix wrong package name in lamp-server tutorial.

source/conf.py
Sometime during last two months, team assiged a new URL, but did not change `canonical_url` in conf.py. This corrects that error.
Signed-off-by: michael vincerra <michael.vincerra@intel.com>
=> Revise canonical_url to newly assigned one in conf.py

source/get-started/ipxe-install.rst
Password hashes in the installer configuration yaml are written as-is to `/etc/shadow`. The backslashes preceding `$` are unnecessary and produce an invalid hash string that will prevent login.
Removing the backslashes makes the sample password work as described.
=> Remove escaping from installer config password hashes
