source/clear-linux/how-to/swupd/run.rst
=> Update the instructions to run swupd to account for auto-update.

source/clear-containers/getting-started.rst
Updated the release version of Docker compatible with the runtime. Removed the
release number of the Clear Containers to avoid having to update it every week.
=> Update the Docker release version.

source/clear-linux/getting-started/bare-metal-install/bare-metal-install.rst
Fixes the broken link to more information about software update
=> fix broken link to swupd

source/clear-linux/virtual-environments/hyper-v.rst
Updating the external links to Microsoft documentation to point to appropriate content and adding the section "Create a virtual network"
=> Update hyper-v links and content

source/clear-linux/bundles/overview.rst
Signed-off-by: ihutchin <ianeta.hutchinson@intel.com>
=> Change to CLOSIA substitution

source/clear-linux/get-started/virtual-machine-install/kvm.rst
Removes merge conflict for kvm branch
Signed-off-by: ihutchin <ianeta.hutchinson@intel.com>
=> Re-writes kvm docs for greater technical accuracy

source/clear-linux/guides/network/custom-clear-container.rst, source/clear-linux/guides/network/network.rst
Signed-off-by: ihutchin <ianeta.hutchinson@intel.com>
=> Adds a new network guide to create a custom container image.

source/clear-linux/guides/maintenance/Telemetry-Enable-Disable.rst, source/clear-linux/guides/maintenance/Telemetry-Enable.rst, source/clear-linux/guides/maintenance/maintenance.rst
Install and enable/disable the telemetrics bundle
=> Telemetry enable/disable guide

source/clear-linux/tutorials/hadoop.rst, source/clear-linux/tutorials/tutorials.rst
=> Add Hadoop use case tutorial.

source/clear-linux/guides/maintenance/enable-user-space.rst
Remove the text about editing the /etc/sudoers file and using vi and visudo
=> Remove visudo command from enable-user-space

source/clear-linux/get-started/bootable-usb/bootable-usb-windows.rst
Fixed a Windows command error. 
-----
Signed-off-by: Bun K Tan <bktan1@bktan1-mac08.jf.intel.com>
=> Fixed a Windows command error

source/clear-linux/guides/maintenance/maintenance.rst, source/clear-linux/guides/maintenance/time.rst
Signed-off-by: ihutchin <ianeta.hutchinson@intel.com>
=> Adds instructions to change the time using systemd-timesyncd.service.

source/clear-linux/reference/collaboration/collaboration.rst, source/clear-linux/reference/collaboration/documentation/basic.rst, source/clear-linux/reference/collaboration/documentation/code.rst, source/clear-linux/reference/collaboration/documentation/cross.rst, source/clear-linux/reference/collaboration/documentation/documentation.rst, source/clear-linux/reference/collaboration/documentation/figures/fibers-1.svg, source/clear-linux/reference/collaboration/documentation/grammar.rst, source/clear-linux/reference/collaboration/documentation/headings.rst, source/clear-linux/reference/collaboration/documentation/hello.c, source/clear-linux/reference/collaboration/documentation/images.rst, source/clear-linux/reference/collaboration/documentation/inline.rst, source/clear-linux/reference/collaboration/documentation/language.rst, source/clear-linux/reference/collaboration/documentation/lists.rst, source/clear-linux/reference/collaboration/documentation/notices.rst, source/clear-linux/reference/collaboration/documentation/parallelism.rst, source/clear-linux/reference/collaboration/documentation/punctuation.rst, source/clear-linux/reference/collaboration/documentation/rest.rst, source/clear-linux/reference/collaboration/documentation/simple.rst, source/clear-linux/reference/collaboration/documentation/steps.rst, source/clear-linux/reference/collaboration/documentation/structures.rst, source/clear-linux/reference/collaboration/documentation/tables.rst, source/clear-linux/tutorials/azure.rst, source/clear-linux/tutorials/wp-install/wp-install.rst
This section contains all the guidelines, rules, examples, and templates needed
to contribute content to the Clear Linux project. The mechanics on how to use
Git to contribute the content will be added in the future.
=> Add documentation contribution guidelines.

source/clear-linux/concepts/concepts.rst, source/clear-linux/get-started/get-started.rst
=> Expand toctree of Concepts and Get started to 2 levels for consistency.

source/clear-linux/tutorials/azure.rst
=> Remove unwanted link to WordPress tutorial.

source/clear-linux/reference/bundles/available-bundles.rst
Removed unnecessary brackets from date.
=> Removed unnecessary brackets.

source/clear-linux/guides/maintenance/increase-virtual-disk-size.rst
Fixed formatting issues:
- Made the "parted" tool warning code-block look awkward.
- Fixed the "parted" tool note.
- Fixed the "Figure 1" statement under "parted tool" section.
=> Fixed formatting issues in the "Increase-virtual-disk-size" document.

source/clear-linux/guides/maintenance/download-verify-uncompress-linux.rst
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
=> Simplify the image checksum validation instructions

source/clear-linux/reference/collaboration/documentation/images.rst, source/clear-linux/reference/collaboration/documentation/language.rst, source/clear-linux/reference/collaboration/documentation/simple.rst, source/clear-linux/reference/collaboration/documentation/tables.rst
Minor changes
Signed-off-by: Ecouzens <evan.couzens@intel.com>
=> copy edit and language update

source/clear-linux/guides/network/dpdk.rst
Modified topic title, heading text, and heading levels.
Deleted prompt character. Replaced # with sudo.
Corrected links to external webpages.
Edited text for active voice and consistency between steps.
=> Edited for grammar, formatting, and text flow.

source/clear-linux/tutorials/telemetry-backend/telemetry-backend.rst
The bulleted list for the flask apps is not rendering correctly, add a line to correct this
=> Fix telemetry-backend rendering issue

source/clear-linux/guides/network/network.rst
=> Fixes structure in network.rst index file.

source/clear-linux/guides/network/vnc.rst
=> Fixes structure issues in Install a VNC Viewer App.

source/clear-linux/guides/network/custom-clear-container.rst
Deleted prompt character. Replaced # with sudo.
Assigned bash role to code blocks with user entries.
Edited text for active voice and consistency between steps.
=> Copy edit for grammar, formatting, and text flow.

source/clear-linux/guides/maintenance/telemetry-enable.rst
Update the link to intel's privacy policy
=> Update telemetry enable link

source/clear-linux/concepts/concepts.rst, source/clear-linux/concepts/restart.rst
=> Added reference to restart in parent concepts. Fixed restart label.

source/clear-linux/get-started/bare-metal-install/bare-metal-install.rst
=> Adds curl command option to download latest CL image.

source/clear-linux/get-started/virtual-machine-install/kvm.rst
=> Adds curl command option to download the latest kvm image

source/clear-linux/get-started/virtual-machine-install/virtualbox.rst
=> Adds curl command option to download the latest live image.

source/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst
=> Adds curl command option to download the latest VMware image.

source/clear-linux/guides/maintenance/time.rst
Changed code-block to bash and made minor text changes.
=> Edited time guide for grammar, formatting, and text flow.

source/clear-linux/reference/how-to-clear-overview.rst, source/clear-linux/reference/reference.rst
Updated Reference file and added training overview.
=> Created how-to-clear-overview as a summary of the How to Clear training.

source/clear-linux/guides/maintenance/download-verify-uncompress-linux.rst, source/clear-linux/guides/maintenance/download-verify-uncompress-mac.rst, source/clear-linux/guides/maintenance/download-verify-uncompress-windows.rst, source/clear-linux/guides/maintenance/image-types.rst
Files: image types; download verify uncompress for Linux, macOS, and Windows
Edits for branding and format. Removed $ prompts.
=> Copy edit of 4 interlinked files in Maint Guide.

source/clear-linux/guides/maintenance/enable-user-space.rst
Signed-off-by: Mahoney <genessa.k.mahoney@intel.com>
=> Copy edits for enable a new user space

source/clear-linux/reference/bundles/available-bundles.rst, source/clear-linux/reference/bundles/bundles.html
=> Updates available bundles and includes pundles.

source/clear-linux/get-started/bootable-usb/bootable-usb-linux.rst
=> Omits prefixes to commands and changes input commands to 'bash'.

source/clear-linux/get-started/virtual-machine-install/virtualbox.rst
=> Adds missing references and associated URIs at bottom

source/clear-linux/get-started/live-image.rst
=> Fixes broken URI for Intel Virtualization Directed I/O

source/clear-linux/tutorials/multi-boot/multi-boot-win.rst
No deferred feedback from PR 108.
=> Copy edit of multi-boot-win for branding, grammar, and format.

source/clear-linux/tutorials/multi-boot/multi-boot-restore-bl.rst
No deferred feedback from PR 108.
=> Copy edit of multi-boot-restore-bl for branding, grammar, and format.

source/clear-linux/tutorials/multi-boot/multi-boot-mint.rst
=> Copy edit of multi-boot-mint for branding, grammar, and format.

source/clear-linux/tutorials/multi-boot/multi-boot-ubuntu.rst
=> Copy edit of multi-boot-ubuntu for branding, grammar, and format.

source/clear-linux/tutorials/multi-boot/multi-boot-sles.rst
=> Copy edit of multi-boot-sles for branding, grammar, and format.

source/clear-linux/tutorials/multi-boot/multi-boot-rhel.rst
=> Copy edit of multi-boot-rhel for branding, grammar, and format.

source/clear-linux/tutorials/multi-boot/multi-boot.rst
=> Copy edit of multi-boot for branding, grammar, and format.

source/clear-linux/tutorials/wp-install/wp-install.rst
Signed-off-by: deb-intel <38864784+deb-intel@users.noreply.github.com>
=> Edits to wp-install.rst

source/clear-linux/get-started/bootable-usb/bootable-usb-linux.rst
=> Revises to specify image file types used for bootable usb drive.

source/clear-linux/tutorials/web-server-install/web-server-install.rst
=> Fixes headers, formatting, and indentation.

source/clear-linux/tutorials/web-server-install/web-server-install.rst
=> Assigns asterisks for third party use and adds CLOSIA.

source/clear-linux/guides/maintenance/mixin.rst
=> Adds punctuation for clarity and fixes sphinx syntax.

source/clear-linux/concepts/swupd-about.rst
I just really don't like that wording
=> swupd: they really are called binary-deltas

source/clear-linux/concepts/concepts.rst, source/clear-linux/concepts/mixer-about.rst
Added mixer concept page. I could use some help to make sure I'm adhering to doc standards, and that I've characterized the mixer correctly.
=> Mixer about

source/clear-linux/get-started/bootable-usb/bootable-usb-windows.rst
=> Corrects Sphinx syntax for accurate rendering.

source/clear-linux/tutorials/docker/docker.rst
Initial proposal to add a tutorial for running Docker on Clear Linux. 
Please feel free to provide any feedback or suggested edits!
=> Add tutorial for Docker on Clear Linux 

source/clear-linux/reference/compatible-kernels.rst
- Linux kernels are updated per clr/bundles active status
- Fulfills JIRA CLEAR 3107
=> Applies grammatical and trademark edits:

source/clear-linux/tutorials/kata.rst
1. Added note for proxy config for docker
2. Improved wording throughout
3. Removed asterisks where they weren't needed
4. Removed reference to version number
=> Updates to Kata Containers tutorial

source/clear-linux/concepts/autospec-about.rst, source/clear-linux/concepts/concepts.rst, source/clear-linux/guides/maintenance/autospec.rst, source/clear-linux/guides/maintenance/maintenance.rst
- CLEAR 3076: Autospec concept draft
- CLEAR 3077: Autospec guide
=> Create autospec guide and autospec-about to fulfill JIRAs:

source/clear-linux/reference/collaboration/documentation/contents.rst, source/clear-linux/reference/collaboration/documentation/rest.rst
=> Adds :contents: directive to Clear Linux collaboration guide.

source/clear-linux/guides/maintenance/autospec.rst
=> Adds two missing values to code-blocks; revises intro paragraph.

source/clear-linux/tutorials/kata.rst, source/clear-linux/tutorials/kata_migration.rst
Updated info for selecting runtime and edits for text flow and clarity.
=> Updated kata and kata_migration tutorials.

source/clear-linux/reference/collaboration/documentation/cross.rst
=> Inserts missing spaces after code-block.

source/clear-linux/clear-linux.rst, source/clear-linux/guides/guides.rst, source/clear-linux/tutorials/tutorials.rst
@intelkevinputnam, Will you please review these added definitions and then advise? I will resend you the email from our discussions on this topic from a few weeks ago. Our PM is driving this change. It should be formally documented. 
@krisdale, Please feel free to comment on this PR. Optional.
=> Define guides vs tutorials

source/clear-linux/guides/maintenance/developer-workstation.rst, source/clear-linux/guides/maintenance/maintenance.rst, source/clear-linux/guides/maintenance/swupd-search.rst
@phmccarty Let's review this in our meeting during WW33.
=> Add dev workstation to cater to developers' needs to find and add minimum bundles. 

source/clear-linux/reference/bundles/available-bundles.rst
=> Adds correct date when bundles were updated.

source/clear-linux/guides/maintenance/validate-signatures.rst
Correct example command lines in the instructions to reflect updated steps/process. See commit notes for details.
=> Correct commands in validate signatures instructions

source/clear-linux/guides/maintenance/mixer.rst
Signed-off-by: Tudor Marcu <tudor.marcu@intel.com>
=> Update mixer docs to current release

source/clear-linux/guides/maintenance/hostname.rst, source/clear-linux/guides/maintenance/maintenance.rst
New guide showing how to edit hostname on Clear Linux.
=> New guide: change hostname

source/clear-linux/concepts/security.rst, source/clear-linux/guides/maintenance/mixer.rst
Opportunistically identified and fixed depth 2 in security.rst in concepts.
=> reduced contents depth to 1 in security.rst and mixer.rst

source/clear-linux/tutorials/web-server-install/web-server-install.rst
=> Continues previous branch: kd-wordpress-tut-reorg

source/clear-linux/tutorials/wordpress/web-server-install.rst
- Applied requested changes from Issue #256 
- Verified changes/full tutorial
- Minor grammatical/text edits for clarity.
=> Updates to "Create a Clear Linux* based web server" tutorial (resolves issue #256). 

source/clear-linux/tutorials/kubernetes.rst
=> Revises CL attributions; applies grammatical and Sphinx-syntax edits.

source/clear-linux/get-started/compatibility-check.rst
- Updated example output from compatibility check script based on updated script
- Updated page title: simplified title, reduce overuse of product name
=> Update compatibility check with updated product name.

source/clear-linux/tutorials/kubernetes.rst
@bktan8 and @joselamego: this update includes your feedback.
@mythi: please have a look also.
=> Streamlined config & run sections and edited text for clarity.

source/clear-linux/tutorials/docker/docker.rst
Added base setup need to get Docker running
Signed-off-by: odwdinc<anthony.pray@gmail.com>
=> Fixed Docker's default configuration.

source/clear-linux/concepts/concepts.rst
- Update intro text to be more concise.
- Update to use new product name substitution
=> Maintenance on Concepts page

source/clear-linux/get-started/bare-metal-install/bare-metal-install.rst
Update the curl script to correctly identify the latest installer image available in the image directory
=> update curl script in bare-metal-install

source/clear-linux/tutorials/greengrass.rst, source/clear-linux/tutorials/tutorials.rst
@bd-dean, @iphutch.  First draft. Please *do not review until you receive my notification* here. In progress.
=> Add greengrass openvino; initial commit. 

source/clear-linux/tutorials/greengrass.rst
- Incremental revision. @bd-dean please review and approve asap.
=> Applies corrections to links and rewording.

source/clear-linux/tutorials/greengrass.rst
=> Applies tables and minor corrections to formatting.

source/clear-linux/tutorials/greengrass.rst
=> Applies trademarks, revises hyperlinks, and re-formats.

source/clear-linux/tutorials/greengrass.rst
- Revises para 2 for conciseness and accuracy, now as list
- Revises section “Complete creating lambda”
- Revises Create User Accounts section
=> Revisions for accuracy and conciseness:

source/clear-linux/tutorials/telemetry-backend/telemetry-backend.rst
Removed the reference to the telemd daemon and made it more generic
=> update telem backend tutorial

source/clear-linux/tutorials/kubernetes.rst
Reviewers: @mythi has provided content, which includes fix for [clearlinux/clr-bundles#81 issue](https://github.com/clearlinux/clr-bundles/issues/81)
=> Kubernetes tutorial: Added details in Install pod network add-on section

source/clear-linux/guides/maintenance/autospec.rst
Correct broken link to next steps section (used old section title).
Add Bundles as a related topic.
=> Correct broken link and add related topic.

source/clear-linux/reference/bundles/bundles.rst
=> Revise header level to test error: mistaken styles inclusion.

source/clear-linux/tutorials/greengrass.rst
=> updated incorrect bundle name

source/clear-linux/concepts/security.rst, source/clear-linux/guides/maintenance/autospec.rst, source/clear-linux/tutorials/docker/docker.rst, source/clear-linux/tutorials/wordpress/web-server-install.rst, source/clear-linux/tutorials/wordpress/wp-install.rst
Now using "make linkcheck" with built-in Sphinx link checking
Fixed a couple broken links and escaped some URLs that were incorrectly being automatically hyperlinked by Sphinx.
=> Results of weekly linkcheck

source/clear-linux/reference/bundles/bundles.html.txt
=> Revises first two <tr>'s of table; includes <style> as test.

source/clear-linux/reference/bundles/bundles.html.txt
=> Removes extra <tr> at top; removes <style>, overwritten by parent css.

source/clear-linux/guides/maintenance/assign-static-ip.rst, source/clear-linux/guides/maintenance/maintenance.rst
=> Add Assign static IP address to maint guide section.

source/clear-linux/tutorials/dlrs.rst
Fixes format error on note and removes unused URL.
=> Cleanup on Deep Learning Reference Stack tutorial

source/clear-linux/tutorials/kubernetes.rst
Revisions and additions:
- Removes section Configure and run Docker + runc
- Removes references to Docker or runc environment
- Adds required installation of containers-basic bundle
=> Kubernetes tutorial revisions

source/index.rst, source/sitemap.rst
Adding sitemap to enable improved and more robust site navigation in final rendered site.
=> Kp add sitemap

source/clear-linux/reference/bundles/bundles.rst
=> Bundles: Adds sentence to direct user to select hyperlink Name.

source/clear-linux/tutorials/kubernetes.rst
=> K8S: Adds internal TOC; troubleshooting detail; fixes format on code-block.

source/clear-linux/reference/bundles/bundles.html.txt
- Capture most recent bundles, pundles added; modified
- Correct URL from packages-descriptions to packages
=> Updates bundles.html.txt to:

source/clear-linux/get-started/bare-metal-install-beta/bare-metal-install-beta.rst
=> bare-metal-install-beta: Fixes syntax error on Fig. 12.

source/clear-linux/get-started/bare-metal-install-beta/bare-metal-install-beta.rst, source/clear-linux/tutorials/kubernetes.rst
- Corrects syntax error in kubernetes.rst in Troubleshooting.
=> bare-metal-install-beta: Revises, reorganizes Main Menu section

source/clear-linux/get-started/virtual-machine-install/virtual-machine-install.rst
Closes #[360](https://github.com/clearlinux/clear-linux-documentation/issues/360)
=> Updated Next Steps in Install CL in VM topic.

source/clear-linux/tutorials/dlrs.rst
=> Adds command to run dlrs image with docker in tutorial

source/clear-linux/tutorials/kubernetes.rst
=> kubernetes tut: Corrects syntax error on lines 206-208.

source/clear-linux/reference/bundles/bundles.html.txt
=> bundles: Updates available bundles per clr-bundles repo

source/clear-linux/get-started/virtual-machine-install/kvm.rst
=> Adds method to copy OVMF.fd from usr/share/qemu/OVMF.fd to wd.

source/clear-linux/tutorials/kubernetes/kubernetes-bp.rst
=> kubernetes-bp: Revises and reformats note on `motd`.

source/clear-linux/guides/maintenance/enable-user-space.rst
=> Reverts to original revision in GH-389.

source/clear-linux/tutorials/greengrass.rst
@bd-dean  Please read over my text edits to be sure the Greengrass tutorial is still accurate. 
@krisdale @intelkevinputnam @mvincerx  I can't replicate the garbled ™ symbol in side nav, unclear if this PR will fix that issue.
=> Minor text edits for branding, punctuation, and TM symbol in title.

source/clear-linux/guides/maintenance/mixin.rst
Overhaul of mixin guide:
- New organization (based on new guide template)
- Updated content (to make current with actual mixin tool)
- Examples have been tested and verified against OS v 27650
=> mixin guide rework

source/clear-linux/get-started/virtual-machine-install/virtualbox.rst
Addresses issue #402 to fix the curl command to download the correct image
=> Update curl command to get live image

source/clear-linux/reference/bundles/bundles.html.txt
- Fixes #404
- Other regex fixes to follow in subsequent PR.
=> Updates bundles, pundles as of 02-20-2019.

source/scripts/_python/utilities/code-blocks.py
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> WIP: scripts: Code Block rst parser

source/clear-linux/guides/maintenance/kernel-development.rst
=> kernel-dev: Editorial revisions, Sphinx corrections, and BKMs.

source/clear-linux/guides/maintenance/mixin.rst
=> Mixin guide: Minor clean up to bring inline with template.

source/scripts/_python/bundle_lister.py, source/scripts/_python/template.html
Modifies extractor function to remove duplicate includes.
- Revises pattern5 regex to include descriptions with special chars.
Resolves consistency in rows for template.
Closes #378.
=> Improve code in bundle_lister.py

source/clear-linux/tutorials/dlrs.rst, source/scripts/_python/utilities/code-blocks.py
Please don't merge until docker hub links are verified.
=> dlrs tutorial update

source/clear-linux/concepts/swupd-about.rst
- Closes #399
- Limit description to swupd functionality and contrasts
=> Revise and simplify swupd-about.

source/clear-linux/guides/maintenance/architect-lifecycle.rst
=> Removes unnecessary header; replaces 2 words with 1.

source/clear-linux/guides/maintenance/architect-lifecycle.rst
=> Revise filepath to figures/architect-lifecycle-1.png; ensure no embedded char errors.

source/clear-linux/get-started/virtual-machine-install/virtual-machine-install.rst
=> Adds virtualbox-clr-installer to toctree of virtual-machine-install.

source/clear-linux/get-started/bootable-usb/bootable-usb.rst
=> updating dd command to add sync for Linux section

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.js, source/clear-linux/guides/maintenance/kernel-development.rst, source/conf.py, source/index.rst
1. Fixed class conflict causing issue with comments in code blocks
2. Fixed include caused by moving a file
3. Changed top level of site to clear-linux/clear-linux.rst
4. Marked old index as orphan
=> Multiple fixes

source/clear-linux/get-started/bare-metal-install/bare-metal-install.rst
- Discontinue support for older txt file and for embedded parsing commands.
=> Remove optional curl method to download installer img.

source/clear-linux/tutorials/kubernetes/kubernetes.rst
=> k8s tut: Add new section on cloud native setup automation.

source/clear-linux/get-started/virtual-machine-install/kvm.rst
=> KVM: Make optional adding desktop-autostart bundle.

source/clear-linux/guides/tooling/swupd-guide.rst
=> swupd-guide: corrects typo; removes trailing spaces.

source/clear-linux/get-started/virtual-machine-install/kvm.rst
=> kvm: Revise conflict between steps 3 and 4.

source/clear-linux/guides/guides.rst, source/clear-linux/tutorials/tutorials.rst
=> Revise, simplify prefaces to guides' and tutorials' landing pages.

source/clear-linux/tutorials/yubikey-u2f.rst
=> yubikey: Add sudo in second command to reload udev rules.

source/clear-linux/tutorials/dars.rst
=> dars: Revise title and all internal refs to Data Analytics Ref Stack.

source/clear-linux/reference/bundles/bundles.rst
=> Corrects typo in intro para.

source/clear-linux/tutorials/dlrs/dlrs.rst
Please see questions inline about Caffe2 and topic levels.
When merged, this will close https://github.com/clearlinux/clear-linux-documentation/issues/468.
=> Completed TCS editorial review

source/clear-linux/get-started/bare-metal-install-desktop/bare-metal-install-desktop.rst
=> Corrects typo in Confirm network connection

source/clear-linux/concepts/security.rst
=> Fixed header underline in security.rst that was causing build error.

source/clear-linux/tutorials/redis.rst, source/clear-linux/tutorials/tutorials.rst
=> Adds redis tutorial with systemctl service check, 2 example use cases

source/clear-linux/guides/guides.rst
Original PR lacked formatting to call out note to the reader.
=> Created an RST note for mixin deprecation notice.

source/clear-linux/guides/tooling/swupd-guide.rst
=> TCS review of swupd-guide

source/clear-linux/get-started/virtual-machine-install/gce.rst
TCS edits to GCE guide for formatting, branding, and grammar.
Follow on to https://github.com/clearlinux/clear-linux-documentation/pull/505
@ttzeng  Please review to be sure technical details are still OK.
=> TCS edits in Creating CL VM on Google Cloud Platform doc

source/clear-linux/guides/tooling/ister.rst, source/clear-linux/reference/image-types.rst
* updated image types to match current offerings
* fixed broken link in ister.rst - now pointing at image-types.rst
=> Update image types to match current offerings.

source/clear-linux/get-started/virtual-machine-install/kvm.rst
update the grep string to isolate and download the -kvm.img file
=> Update KVM download script

source/clear-linux/concepts/telemetry-about.rst
Remove link to the features/telemetry, it no longer exists
=> Update telemetry about

source/clear-linux/guides/tooling/autoproxy.rst, source/clear-linux/guides/tooling/autospec.rst
These are simple editorial revisions.
=> Dm autospec guide editorial

source/clear-linux/guides/tooling/ister.rst
Signed-off-by: douglasm <doug.martin@intel.com>
=> Changed ister.rst for trademarks, branding, and editorial issues.

source/clear-linux/tutorials/dlrs/dlrs.rst
This will address issues #560 & #559.
=> Add link for launcher.py and note MKL HW reqs for DLRS tutorial.

source/clear-linux/guides/tooling/debug.rst
=> Editorial changes to debug.rst

source/clear-linux/get-started/bare-metal-install-desktop/bare-metal-install-desktop.rst
=> Adds note to clarify BIOS behavior if installing on multiple partitions.

source/clear-linux/guides/tooling/swupd-guide.rst
=> swupd-guide editorial changes

source/clear-linux/get-started/virtual-machine-install/kvm.rst
Updated doc. to reflect any changes.
=> Retested QEMU-KVM doc. against latest Clear and 3rd-party distros.

source/clear-linux/FAQ/faq.rst, source/sitemap.rst
Addresses issue https://github.com/clearlinux/clear-linux-documentation/issues/599
=> Added FAQ to sitemap and shortened FAQ title text to "FAQ."

source/clear-linux/tutorials/dlrs/dlrs.rst
This PR needs discussion before merging.
=> Add a note about running stack on other Linux distros

source/clear-linux/tutorials/nvidia.rst
=> NVIDIA; Trademark, branding, and editorial changes

source/clear-linux/guides/maintenance/download-verify-decompress-mac.rst
=> Corrects Step 4 command to verify integrity.

source/clear-linux/guides/telemetrics/telem-guide.rst
=> Add section on settign a static machine id to telem-guide

source/clear-linux/get-started/bare-metal-install-server/bare-metal-install-server.rst
=> bare-metal-install-server.rst: fixed cross-ref to autoproxy

source/clear-linux/guides/deploy-at-scale.rst
=> deploy-at-scale: fixed cross-ref and made minor formatting and editorial changes.

source/clear-linux/get-started/bare-metal-install-desktop/bare-metal-install-desktop.rst, source/clear-linux/get-started/bare-metal-install-server/bare-metal-install-server.rst, source/clear-linux/get-started/bootable-usb/bootable-usb.rst, source/clear-linux/get-started/virtual-machine-install/hyper-v.rst, source/clear-linux/get-started/virtual-machine-install/kvm.rst, source/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer.rst, source/clear-linux/get-started/virtual-machine-install/vmw-player-preconf.rst, source/clear-linux/get-started/virtual-machine-install/vmw-player.rst, source/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst
Basic link clean up in advance of translation of content.
- Removed unused links
- Updated links defined as named refs to use simple text e.g. name of linked content
instead of narrative text.
- Minor text edits to accomodate minor changes to name ref links.
=> Get Started section link clean up

source/clear-linux/get-started/get-started.rst, source/clear-linux/get-started/install-configfile.rst
@bktan8  This new guide uses your text from #523, please let me know if you have any feedback.
=> New guide: how to install using config file

source/clear-linux/tutorials/dars.rst
=> Add link for terms of use. 

source/clear-linux/reference/system-requirements.rst
=> system-requirements: #610: Corrected trademarks use

source/clear-linux/get-started/bootable-usb/bootable-usb.rst, source/clear-linux/get-started/compatibility-check.rst, source/clear-linux/get-started/get-started.rst, source/clear-linux/get-started/install-configfile.rst, source/clear-linux/get-started/virtual-machine-install/gce.rst, source/clear-linux/get-started/virtual-machine-install/hyper-v.rst, source/clear-linux/get-started/virtual-machine-install/kvm.rst, source/clear-linux/get-started/virtual-machine-install/virtual-machine-install.rst, source/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer.rst, source/clear-linux/get-started/virtual-machine-install/vmw-player-preconf.rst, source/clear-linux/get-started/virtual-machine-install/vmw-player.rst, source/clear-linux/get-started/virtual-machine-install/vmware-esxi-install-cl.rst, source/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst, source/clear-linux/reference/compatible-kernels.rst
Basic cleanup and standardization of intro in preparation for translation. 
Minor refactor of some intros to simplify sentences/word choice.
=> Get Started cleanup for translation

source/clear-linux/guides/telemetrics/telem-guide.rst
=> Telemetry guide: made editorial, formatting, and spelling revisions.

source/clear-linux/tutorials/docker/docker.rst
=> Docker.rst. Removed broken link and corrected trademark errors.

source/clear-linux/guides/maintenance/kernel-modules-dkms.rst
=> kernel-modules-dkms.rst: Fixed broken link to mixer.rst

source/clear-linux/tutorials/kubernetes/kubernetes.rst
=> kubernetes.rst: Revised link to stateless.rst, formatting, and trademarks.

source/clear-linux/tutorials/wordpress/web-server-install.rst
=> web-server-install.rst: Revised link to stateless.rst and added trademarks.

source/clear-linux/get-started/bare-metal-install-desktop/bare-metal-install-desktop.rst
=> live-desktop: Revise Table 1 to clarify labels, filesystem, and default verbiage.

source/clear-linux/get-started/bare-metal-install-server/bare-metal-install-server.rst
=> live-server: Revise Table 1 to clarify labels, filesystem, and default verbiage.

source/clear-linux/guides/maintenance/query-upstream.rst
Addresses Issue #527  
Added to Guides > Maintenance 
@bktan8 @mvincerx  Please have a look. 
=> New guide: how to query upstream CL repo

source/clear-linux/guides/maintenance/architect-lifecycle.rst, source/clear-linux/guides/maintenance/assign-static-ip.rst, source/clear-linux/guides/maintenance/bulk-provision.rst, source/clear-linux/guides/maintenance/cpu-performance.rst, source/clear-linux/guides/maintenance/developer-workstation.rst, source/clear-linux/guides/maintenance/enable-user-space.rst, source/clear-linux/guides/maintenance/fix-broken-install.rst, source/clear-linux/guides/maintenance/hostname.rst, source/clear-linux/guides/maintenance/increase-virtual-disk-size.rst, source/clear-linux/guides/maintenance/kernel-development.rst, source/clear-linux/guides/maintenance/kernel-modules-dkms.rst, source/clear-linux/guides/maintenance/kernel-modules.rst, source/clear-linux/guides/maintenance/restart.rst, source/clear-linux/guides/maintenance/time.rst, source/clear-linux/guides/maintenance/validate-signatures.rst
Clean up in preparation for translations  …
- Standardize page formatting (use of intro sentence, TOC tree, etc)
- Simplify intro sentences, remove idioms, etc
- Standardize use of roles (remove use of `` and * for emphasis on special words or options)
- Misc clean up (opportunistic)
=> Clean up of maintenance guides in prep for translation

source/clear-linux/get-started/virtual-machine-install/vmw-player.rst
* Reworded paragraph and linking text.
=> vmw-player-preconf.rst: replaced include with ref to download-verify-decompress

source/clear-linux/get-started/virtual-machine-install/vmware-esxi-install-cl.rst
=> vmware-esxi-install-ci: replaced include with ref to download-verify-decompress

source/clear-linux/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst
* Reworded paragraph and linking text.
=> vmware-exsi-preconfigured-ci-image: replaced include with ref to download-verify-decompress

source/clear-linux/get-started/bare-metal-install-desktop/bare-metal-install-desktop.rst, source/clear-linux/get-started/bare-metal-install-server/bare-metal-install-server.rst, source/clear-linux/guides/maintenance/download-verify-decompress.rst
=> Get Started - Minor clean up in preparation for translation.

source/clear-linux/guides/maintenance/validate-signatures.rst
=> Validate Signatures: Minor editorial revisions.

source/clear-linux/guides/maintenance/bulk-provision.rst
=> Escaped local URLs that were being turned into links.

locale/zh_CN/LC_MESSAGES/get-started/bootable-usb/bootable-usb.po, locale/zh_CN/LC_MESSAGES/get-started/compatibility-check.po, locale/zh_CN/LC_MESSAGES/get-started/get-started.po, locale/zh_CN/LC_MESSAGES/get-started/install-configfile.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/gce.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/hyper-v.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/kvm.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/virtualbox-cl-installer.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/vmw-player-preconf.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/vmw-player.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/vmware-esxi-install-cl.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.po, locale/zh_CN/LC_MESSAGES/guides/maintenance/increase-virtual-disk-size.po, locale/zh_CN/LC_MESSAGES/reference/system-requirements.po
Added translated ZH-CN content for the Get Started and updated content from the localization team
=> Rtd theme l10n

source/clear-linux/guides/tooling/swupd-guide.rst
=> swupd-guide.rst: Minor formatting changes

source/clear-linux/tutorials/nvidia.rst
=> nvidia.rst: Minor editorial and formatting changes.

source/clear-linux/guides/maintenance/cpu-performance.rst
Combine `systemctl enable` and `systemctl start` commands with a single `systemctl enable --now` command.
https://www.freedesktop.org/software/systemd/man/systemctl.html#--now for more information
=> Update cpu-performance systemctl command

source/clear-linux/tutorials/kata.rst
* Added TOC after opening sentence
* Added Description heading
* Moved remaining description under Description
* Other minor editorial/formatting revisions.
=> Kata tutorial: Minor editorial revisions.

source/clear-linux/tutorials/kubernetes/kubernetes.rst
=> kubernetes tutorial: minor editorial revisions.

source/clear-linux/tutorials/aws-web/aws-web.rst
* Capitalization of Figure references
* Revised word choices
* Added trademark notation for Amazon Web Services
=> aws-web.rst: Minor editorial and trademark changes:

source/clear-linux/guides/network/openssh-server.rst, source/clear-linux/reference/reference.rst
=> Made changes per Issue 664: moved topic, edited text

source/index.rst
Updated text to improve clarity re type of content per section. Collab effort with @DougTW .
=> Update landing page text for clarity per request.

source/clear-linux/tutorials/kubernetes/kubernetes.rst
=> k8s tutorial: Adds references to cloud-native-setup; corrects URL.

requirements.txt, source/conf.py
=> Add requirement and config for sphinx-sitemap

source/about.rst, source/guides/index.rst
Revisions to new about page. Added section link to guides index, for reference from about page.
A collaborative effort with @DougTW 
=> About page edits

source/_themes/otc_tcs_sphinx_theme/layout.html
=> Correction to GA snippet

source/_themes/otc_tcs_sphinx_theme/layout.html
=> GA edits for spaces

source/_scripts/_python/requirements.txt
=> Upgrades to Jinja2 2.10.1, dependency for bundle_lister.py.

source/get-started/bare-metal-install-desktop.rst, source/get-started/bootable-usb.rst, source/get-started/virtual-machine-install/gce.rst, source/get-started/virtual-machine-install/hyper-v.rst, source/get-started/virtual-machine-install/virtualbox-cl-installer.rst, source/get-started/virtual-machine-install/vmware-esxi-install-cl.rst, source/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst, source/guides/clear/autospec.rst, source/guides/clear/ister.rst, source/guides/clear/telemetrics.rst, source/substitutions.txt, source/tutorials/docker.rst
=> Minor grammatical updates requested in support of upcoming translated content.

source/_scripts/_python/template.html
=> Applies default css for tables to available bundles.

source/conf.py
Output will look like this:  © Copyright 2019. Last updated on <date>.
=> Edited conf.py to fix copyright statement.

source/_themes/otc_tcs_sphinx_theme/layout.html, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
=> Added trademark disclaimer at the bottom of each page.

source/get-started/bootable-usb.rst
=> Minor edit to bootable-usb to support translations.

source/_scripts/_python/bundle_lister.py, source/_scripts/_python/template.html, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
- Add regex PATTERN4 to capture bundle status values
- Add code to process capture groups in for loop
- Rename bundler() to main() to follow Python convention
- Add conditional blocks to filter tags based on below status indicators
- Add css classes for active-status, wip-status, and pending-delete-status
- Closes #747
=> Add code to show status and assign status color-code for available bundles.

source/guides/stacks/dlrs.rst, source/tutorials/dlrs.rst
=> Adds back dlrs.rst in guides/stacks/ to avoid redirect issues.

source/guides/index.rst, source/guides/stacks/dlrs.rst
=> Add label link to dlrs2 for stacks/guides

source/_scripts/_python/template.html
=> Adds missing space in conditional statement in _python/template.html

locale/zh_CN/LC_MESSAGES/FAQ/index.po, locale/zh_CN/LC_MESSAGES/get-started/cloud-install/aws-web.po, locale/zh_CN/LC_MESSAGES/get-started/virtual-machine-install/virtualbox-cl-installer.po, locale/zh_CN/LC_MESSAGES/guides/clear/telemetrics.po, locale/zh_CN/LC_MESSAGES/guides/maintenance/download-verify-decompress.po, locale/zh_CN/LC_MESSAGES/guides/maintenance/resource-limits.po, locale/zh_CN/LC_MESSAGES/tutorials/flatpak.po, source/get-started/virtual-machine-install/virtualbox-cl-installer.rst
1. Changed link to inline and updated in .po for virtualbox-cl-installer
2. Fixed out of date .po files affected by sphinx-intl update required to update link above.
=> Changed link in English docs to enable localized version of link in Chinese language

source/conf.py
=> Added 简体中文 (Simplified Chinese) to language picker.

source/get-started/bootable-usb.rst
- Closes #730
Signed-off-by: Michael Vincerra
<michael.vincerra@intel.com>
=> bootable-usb: Line-edits to clarify macOS commands and process desc.

source/get-started/virtual-machine-install/kvm.rst
=> fixed typo

source/tutorials/flatpak.rst
=> flatpak.rst: minor editorial changes

source/_themes/otc_tcs_sphinx_theme/layout.html
- Update to use regex to match hostname for cross domain tracking
- Update to set useAnchor to true (to add session id to anchor instead of query)
- Update to use https when adding analytics.js
=> Updated GA tracking snippet:

source/tutorials/kubernetes-bp.rst
Changes include: 
- added standardized introduction paragraph, description, and prerequisites
=> Kubernetes-bp.rst editorial changes

source/_scripts/_python/linkcheck/link-whitelist.txt, source/get-started/virtual-machine-install/vmware-esxi-install-cl.rst, source/get-started/virtual-machine-install/vmware-esxi-preconfigured-cl-image.rst, source/guides/clear/swupd.rst
* Added one link to whitelist (nvidia downloads)
* Added "/" to download images link
* Updated to swupd update link
=> Fixes several links that were failing

source/get-started/cloud-install/azure.rst
- added standardized introduction paragraph, description, and prerequisites
- revised first usage of Microsoft Azure to have disclaimer asterisk
=> azure.rst: Editorial changes

source/tutorials/yubikey-u2f.rst
- rearranged standardized introduction paragraph and added a description
- rearranged some content
- moved contents directive closer to the start of the document
=> yubikey-u2f.rst: editorial changes

source/guides/stacks/dlrs.rst
Signed-off-by: Beth Dean <beth.e.dean@intel.com>
Closes #767 Closes #727
=> Fix incorrect image name; update link to benchmark

source/tutorials/fmv.rst
- added standardized introduction paragraph and description
- revised some steps to be continuations of other steps
=> fmv.rst: Editorial revisions

source/tutorials/apache-hadoop.rst
- added standardized introduction paragraph and description
- revised some steps to be continuations of other steps 
=> apache-hadoop.rst: Editorial changes

source/tutorials/smb.rst
- added inline text formatting directives
- simplified prerequisites section
- added disclaimer notation for third-party trademarks/brands
=> smb.rst: Editorial changes

README.rst
=> Updated readme to reflect recent changes and latest doc BKMs.

source/reference/system-requirements.rst
=> Corrects SIMD extensions from 4.1 to 4.2 in system-requirements

source/tutorials/smb-desktop.rst
- added disclaimer notation for third-party trademarks/brands
- revised step to present tense and to show result of previous step's action
=> smb-desktop.rst: Editorial changes

source/tutorials/proxy.rst
- modified standardized introduction paragraph 
- simplified prerequisites section
- added disclaimer notation for third-party trademarks/brands
=> proxy.rst: Editorial changes

source/tutorials/archive/kata_migration.rst
- modified standardized introduction paragraph and description
- added prerequisites section
=> kata migration.rst: Editorial changes

source/guides/stacks/dbrs.rst
Can't merge until updates to links once release has been confirmed.
=> Create DBRS guide

source/guides/stacks/dbrs.rst
=> Add link to terms of use

source/guides/stacks/dbrs.rst
Closes #818 
Also updates the use of Cassandra to Apache Cassandra.
=> Add link to benchmark results to DBRS

source/guides/network/dpdk.rst
"sudo echo > " will not work as the current shell will make the redirection and it doen't have the root privileges
=> Replace "sudo echo >" with "echo | sudo tee"

source/tutorials/kubernetes.rst
Provides more background on commands, corrects errors. Closes #571
=> Update K8S tutorial for clarity

source/get-started/virtual-machine-install/parallels.rst
- Moved tutorial to Get Started virtual install section
- Updated title and intro to be consistent with other get started guides
- Updated reference to 'tutorial' to be 'guide'
Closes #776
=> Move Parallels tutorial to Get Started

source/guides/clear/autospec.rst
=> Add Example 5 for updating existing package in autospec

source/guides/clear/autospec.rst
=> Adds youTube video tutorial for autospec to guide page.

source/tutorials/openvino.rst
=> Remove title case for sample application and fix typo in OpenVINO for DL.

source/get-started/bootable-usb.rst
Added a note to keep label as `CLR_ISO` which might save some time for me :)
This is somehow related to https://github.com/clearlinux/clr-installer/pull/554
=> bootable-usb.rst small improvement

source/get-started/bootable-usb.rst
=> Apply wording corrections to to bootable-usb.

source/_html_extra/_errors/403.html, source/_html_extra/_errors/404.html, source/conf.py
- Added static html pages for 404 and 403 server responses.
- Added conf.py setting html_extra_path to copy static _errors folder
with static 404/403 files into build output
=> Add custom 404 and 403 pages.

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.js
* Fixes behavior and appearance of permalinks in collapsible sections.
* Fixes links to collapsible sections so that header is now target.
* Adds ability to create code blocks with prepended "$" that won't be copied (wip).
=> Fixes to custom Spinx theme on top of RTD

source/_html_extra/_errors/403.html, source/_html_extra/_errors/404.html
- Update paths to search and image to be absolute URLs
- Correct typo in CSS
=> Update 400 http error pages

source/conf.py
=> Removes Previous/Next buttons on each page of docs.

source/get-started/bare-metal-install-desktop.rst, source/get-started/bare-metal-install-server.rst, source/get-started/bootable-usb.rst
and minor change to "emphasis" ending line number in bootable.rst.
=> Remove reference to "decompress" in bare metal installer docs.

source/tutorials/nvidia.rst
This PR updates the NVIDIA driver documentation with:
- Simplified section heads by positioning some steps strategically.
- A note regarding NVIDIA Optimus systems
- A section on brightness control quirks
- Add step to make nvidia-settings desktop icon appear
Closes https://github.com/clearlinux/clear-linux-documentation/issues/831
=> Update NVIDIA drivers documentation

source/guides/stacks/dars.rst
Closes #862 
This is a major update to add examples for Hadoop and Kubernetes, in conjunction with the V2 release of DARS.
=> Add examples for Hadoop and Kubernetes

source/guides/network/ipxe-install.rst
- Add additional text defining the minimum system requirements for the PXE client
- closes #872
=> Update PXE tutorial to add client requirements

source/get-started/virtual-machine-install/hyper-v.rst
Reorganized text and edited per instructions in Issue #774.
=> Editorial changes in Hyper-v guide for grammar and formatting.

source/guides/stacks/dlrs.rst
Makes the Stack features section more standard & rename to Releases.
=> Clean up DLRS release section

source/get-started/virtual-machine-install/virt-manager.rst
Completed text cleanup referenced in #881  
=> Editorial changes for grammar and formatting.

README.rst
=> Correct obsolete URL for contribution guidelines.

source/tutorials/multi-boot/dual-boot-linux.rst
=> Removes 1 empty space to assure proper render in dual-boot-linux.

source/guides/maintenance/enable-systemd-boot-menu.rst
=> Added bash console directive for the clr-boot-manager commands.

source/guides/stacks/dlrs.rst
=> Update URL for kfctl_k8s_istio.yaml

source/tutorials/php.rst
Fixed nesting problem in #888 
Made editorial changes for structure & formatting to align with other tutorials.
=> Fixed nesting issue.

source/get-started/bare-metal-install-desktop.rst
Closes https://github.com/clearlinux/clear-linux-documentation/issues/891
=> Revise bullet to clarify offline install option, bare-metal-install-desktop

.github/workflows/greetings.yml
=> Remove empty spaces and check syntax based on prev failures.

requirements.txt, source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css, source/conf.py, source/guides/stacks/dbrs.rst
Implemented tabs on the Stacks DB reference stack guide.
Expecting more changes based on @bd-dean's feedback. 
=> WIP Add support for sphinx-tabs and update stacks guides with tabs. 

Makefile, README.rst
=> Add instructions for virtualenv in readme; revise make venv target in Makefile 

README.rst
=> Resolve rendering error in README.

source/get-started/bare-metal-install-desktop.rst, source/get-started/bare-metal-install-server.rst
on baremetal installation guides.
=> Troubleshooting tip on how to erase LVM partitions

source/get-started/virtual-machine-install/hyper-v.rst
This PR doesn't close pr 896 because there are multiple files to be fixed. Last PR will close pr 896.
=> hyper-v.rst: Fixes Figure caption indent

source/guides/maintenance/fix-broken-install.rst
Added steps to mount and unmount the /boot partition during the repair process.
=> Updated to mount the /boot partition

source/guides/maintenance/fix-broken-install.rst
- Closes #948  
- Remove include per request from @bktan8
- Make concise the Prereq's
=> Simplify section "Boot a live desktop image to fix..." in fix-broken-install

source/get-started/virtual-machine-install/parallels.rst
=> parallels.rst: Fixes Figure caption indent Closes #896

source/guides/stacks/dlrs.rst
=> Replace stacks-tensorflow-mkl with stacks-dlrs-mkl in dlrs

source/guides/maintenance/developer-workstation.rst
=> Add improved role descriptions and bundles to developer-workstation

source/get-started/cloud-install/digitalocean.rst
=> Minor fixes to DigitalOcean doc.

source/guides/stacks/dlrs.rst
Adds updated information for the DLRS V5 Release, and updates instructions for using Selden and OpenVINO to serve models.
=> Update for DLRS V5 release

source/guides/network/wifi.rst
=> Update to wifi guide to include wpa_supplicant.

source/guides/stacks/dbrs.rst, source/tutorials/yubikey-u2f.rst
=> Fixed two broken links found in weekly check.

source/guides/stacks/dlrs.rst
URL points to incorrect github repo for stacks readme.
=> Update readme URL and remove redundant Seldon section

source/guides/maintenance/cpu-performance.rst
add thermal configuration section for cpu-performance page
=> cpu-performance.rst: add thermal configuration section

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Add appropriate rst-class before figure:
.. rst-class:: dropshadow
=> Adds support for drop shadows on figures

source/guides/clear/mixer.rst
=> Prepends `mixer build` commands with sudo for successful execution.

source/index.rst
=> Adds IRC channel to link to freenode.net.

source/tutorials/vmware-workstation.rst, source/tutorials/vmware_workstation.rst
Add new VMware Workstation Pro tutorial.
Closes #462
=> New VMware Workstation tutorial

source/get-started/bootable-usb.rst, source/guides/maintenance/fix-broken-install.rst, source/tutorials/multi-boot/dual-boot-win.rst
=> Update lsblk commands to make it easier to identify devices.

source/get-started/bare-metal-install-desktop.rst, source/get-started/bare-metal-install-server.rst, source/reference/system-requirements.rst
=> Add min. required disk space for bare-metal-install-desktop and bare-metal-install-server

source/guides/stacks/dbrs.rst, source/tutorials/redis.rst
1. Fixes link to http://try.redis.io in redis tutorial.
2. Fixes link to pmem-csi readme in DBRS stack guide.
=> Fix links caught in weekly automated check.

source/guides/clear/mixer.rst
=> Update mixer build image to use clr-installer.

source/guides/network/time.rst
When I tried this I had an error when I tried to set ntp to true that polkit was missing. Adding that bundle allowed the step to complete.
=> Updated time.rst

source/tutorials/multi-boot/dual-boot-win.rst
=> Dual-boot win - add link to server install as another option.

source/get-started/cloud-install/qingcloud.rst
=> Updates based on native Chinese speaker review.

source/tutorials/nvidia.rst
=> Update NVIDIA tutorial to recommend LTS kernel

source/_themes/otc_tcs_sphinx_theme/static/tcs_theme.css
Includes adjustments to make sure everything fits.
=> Sets max width of content to 1100 pixels

source/tutorials/nvidia.rst
Minor edit. Closes https://github.com/clearlinux/clear-linux-documentation/issues/1032
=> Add missing mkdir command in nvidia doc

source/tutorials/kata.rst
This PR updates the kata document to have instructions for opting-in to use kata since it is no longer the default runtime.
Closes https://github.com/clearlinux/clear-linux-documentation/issues/1026
=> Update kata doc after default runtime change

source/tutorials/nvidia.rst
muchas importante
@puneetse @lebensterben
=> Makes driver find application profiles

source/guides/maintenance/configure-hugepages.rst
Closes #1005
Signed-off-by: Adams, Eric <eric.adams@intel.com>
=> Adds hugepages config guide to explain defaults and config settings

source/guides/network/openssh-server.rst
=> Update instructions for X11 forwarding and SFTP

source/guides/stacks/dbrs.rst
=> Add memcached instructions for v2.0

source/guides/clear/mixer.rst, source/guides/clear/swupd-3rd-party.rst
=> Create, Install, and Manage 3rd-party Bundles

source/get-started/ipxe-install.rst
=> Update nginx setting for iPXE doc

source/guides/stacks/dbrs.rst
This is the dbrs fix for #1087
=> Fix broken link

source/guides/clear/stateless.rst
=> Minor updates to the Stateless doc.

source/guides/kernel/kernel-boot-msg.rst
=> Capture kernel boot messages in journal.

source/FAQ/index.rst, source/about.rst
* Closes #1102
* Creates component list table and reorganizes content coherently.
* Applies organizational edits, line edits for consistency of voice.
=> Provide overview of CL architecture, including rationale.

source/guides/maintenance/fix-broken-install.rst
=> Update fix broken installation

source/guides/clear/swupd-3rd-party.rst
=> Minor updates to swupd 3rd-party

source/tutorials/nvidia.rst
This closes https://github.com/clearlinux/clear-linux-documentation/issues/1101
=> nvidia.rst: Added a section on slow boot times

source/guides/stacks/dlrs.rst
Please publish Tuesday April 21.  Closes #1122
=> Update DLRS guide for v6 release

source/guides/stacks/dlrs.rst
=> Update DLRS guide with correct V6 link

source/conf.py
Updated copyright string in conf.py to be consistent with copyright used on clearlinux.org
=> Update copyright to be consistent with clearlinux.org.

source/get-started/cloud-install/import-clr-aws.rst
=> Fix "Import Clear Linux Image and Launch Instance on AWS" issues

.github/workflows/linkcheck.yml
=> Add tri-weekly check of links

source/guides/clear/performance.rst
New doc providing an outline of the approach and tactics used by CL
for performance optimizations.
Resolves #801
=> Performance doc

source/tutorials/redis.rst
=> Update Redis tutorial

source/tutorials/hpc.rst, source/tutorials/lamp-server.rst, source/tutorials/wordpress.rst
=> Shorten WordPress, LAMP, HPC tutorial titles

source/tutorials/index.rst
=> Revise tutorial index to Low, Moderate, Difficult per CL meeting.

source/tutorials/index.rst
=> Add 3 tutorials to tutorials index for discoverability.

requirements.txt
=> Update to Sphinx 2.2.0 to update jquery.js to 3.4.1

source/get-started/virtual-machine-install/hyper-v.rst, source/get-started/virtual-machine-install/kvm.rst, source/get-started/virtual-machine-install/virt-manager.rst, source/get-started/virtual-machine-install/virtualbox-cl-installer.rst, source/get-started/virtual-machine-install/vmw-player.rst
=> Update TM&B in Get Started section of docs

source/about.rst
- Add asterisk for 3rd party trademarks
- Remove redundant asterisks (only first use needed)
=> Update TM&B in About section of docs

source/reference/compatible-hardware.rst, source/reference/system-requirements.rst
- Minor corrections to a couple of Intel trademarks
- Add required nouns to Intel trademarks
- Remove duplicate '* Other names and brands ...'
- Remove SKU from table header in compatible hardware (as SKU is only part of the name)
=> Update TM&B in Reference section of docs

source/get-started/bare-metal-install-desktop.rst, source/get-started/bare-metal-install-server.rst
- Improve discoverability of install-configfile
- Closes #1083
=> Adds reference in bare-metal-install-* to use YAML config file to install

source/guides/clear/compatible-kernels.rst, source/guides/clear/performance.rst, source/guides/clear/security.rst, source/guides/maintenance/cpu-performance.rst, source/guides/stacks/dars.rst, source/guides/stacks/dbrs.rst, source/guides/stacks/dlrs-inference.rst, source/guides/stacks/dlrs.rst, source/guides/stacks/greengrass.rst, source/guides/stacks/mers.rst
- Update/correct product names in text per Intel guidance
=> Update TM&B in guides section of docs

source/tutorials/apache-spark.rst, source/tutorials/broadcom.rst, source/tutorials/docker.rst, source/tutorials/flatpak.rst, source/tutorials/fmv.rst, source/tutorials/kubernetes.rst, source/tutorials/lamp-server.rst, source/tutorials/nvidia.rst, source/tutorials/openfaas.rst, source/tutorials/php.rst, source/tutorials/redis.rst, source/tutorials/wordpress.rst
- Update some 3rd party trademark attributions
=> Update TM&B in tutorials section of docs

source/FAQ/index.rst
Closes https://github.com/clearlinux/clear-linux-documentation/issues/1194
=> Update FAQ ZFS question with link to tutorial

source/guides/maintenance/configure-hugepages.rst
'explicitely' should be explicitly
=> fix misspelling

source/tutorials/kubernetes.rst
Merge of updates into publish branch.
=> Fix #use-your-cluster link on doc (#1228)

source/tutorials/kubernetes.rst
Change sed script to use var instead of dev.
=> Fix command to disable swap

source/conf.py
Signed-off-by: michael vincerra <michael.vincerra@intel.com>
=> Update copyright of documentation from 2021 to 2022.

source/conf.py
=> Fixes version picker for new documentation location.

.github/workflows/publish.yml
=> Adds .nojekyll to output for use with GitHub pages.
